import type { Occasion, PlanCategory, PlanOption, ParsedSituation } from "./types";
import { buildExperienceProfile } from "./experience";
import { KAKAO_CATEGORY_SEARCH } from "./place-utils";

type CatalogEntry = Omit<PlanOption, "id" | "href" | "location" | "imageUrl" | "imageAlt" | "reason" | "venueType" | "reservationRequired"> & {
  key: string;
  categories: Occasion[];
  regions?: string[];
  query?: string;
  location?: string;
  imageUrl?: string;
  imageAlt?: string;
  reason?: string;
  venueType?: PlanOption["venueType"];
  reservationRequired?: boolean;
};

/**
 * 실제 가게를 아직 못 찾았을 때 여는 링크. 네이버 통합검색은 장소가 아니라 블로그 글이 뜨는
 * 일이 많아서, 지도에서 바로 가게 목록이 보이는 카카오맵 검색으로 보낸다.
 *
 * 검색어로 카탈로그 제목("정원 한옥 독특한 건축 분위기 좋은 로컬 다이닝")을 그대로 넘기면
 * 지도는 그 문장을 상호명처럼 찾아 0건을 준다 — 링크를 눌러도 아무것도 안 나오던 이유가 이거였다.
 * 지도에서 실제로 결과가 나오는 짧은 업종어로만 보낸다.
 */
const encodedSearch = (category: PlanCategory, region: string) => {
  const keyword = KAKAO_CATEGORY_SEARCH[category].keywords[0] ?? "";
  return `https://map.kakao.com/?q=${encodeURIComponent(`${region} ${keyword}`.trim())}`;
};

const giftSearch = (query: string) =>
  `https://gift.kakao.com/search/result?query=${encodeURIComponent(query)}`;

const visuals: Record<PlanCategory, Pick<PlanOption, "imageUrl" | "imageAlt" | "venueType" | "reservationRequired">> = {
  activity: {
    imageUrl: "https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=1200&q=82",
    imageAlt: "은은한 조명의 미술 전시 공간",
    venueType: "indoor",
    reservationRequired: true,
  },
  cafe: {
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=82",
    imageAlt: "햇살이 드는 차분한 카페",
    venueType: "indoor",
    reservationRequired: false,
  },
  meal: {
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=82",
    imageAlt: "따뜻한 조명의 저녁 식사 테이블",
    venueType: "indoor",
    reservationRequired: true,
  },
  view: {
    imageUrl: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=82",
    imageAlt: "도시 불빛이 보이는 야경",
    venueType: "outdoor",
    reservationRequired: false,
  },
  lodging: {
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=82",
    imageAlt: "편안한 조명과 전망이 있는 숙소",
    venueType: "indoor",
    reservationRequired: true,
  },
  cake: {
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=82",
    imageAlt: "작고 섬세한 기념일 케이크",
    venueType: "indoor",
    reservationRequired: true,
  },
  flower: {
    imageUrl: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1200&q=82",
    imageAlt: "따뜻한 색감의 계절 꽃다발",
    venueType: "indoor",
    reservationRequired: true,
  },
  gift: {
    imageUrl: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1200&q=82",
    imageAlt: "정갈하게 포장된 작은 선물",
    venueType: "indoor",
    reservationRequired: false,
  },
  moment: {
    imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=82",
    imageAlt: "손으로 쓴 따뜻한 편지",
    venueType: "mixed",
    reservationRequired: false,
  },
};

const entries: Record<PlanCategory, CatalogEntry[]> = {
  activity: [
    {
      key: "immersive-night",
      title: "빛과 공간에 몰입하는 야간 경험",
      subtitle: "미디어아트·특별 개방·기간 한정 전시를 우선 탐색",
      price: 52000,
      durationMinutes: 95,
      provider: "현재 운영 중인 특별 경험 확인",
      handoffKind: "search",
      badge: "오늘의 발견",
      notes: ["운영 기간과 마지막 입장 시간을 반드시 확인하세요", "기간 한정 여부가 확인된 경우에만 그렇게 표시해요"],
      categories: ["birthday", "anniversary", "date", "proposal", "thanks", "special"],
      query: "기간 한정 몰입형 미디어아트 야간 전시 특별 개방",
      reason: "혼자 검색하면 놓치기 쉬운 빛·공간 중심 경험을 하루의 첫 발견으로 두었어요.",
      venueType: "indoor",
    },
    {
      key: "curated-exhibition",
      title: "둘이 천천히 보는 전시 한 편",
      subtitle: "대화를 시작하기 좋은 90분 · 실내 동선",
      price: 36000,
      durationMinutes: 90,
      provider: "현재 전시와 예매 확인",
      handoffKind: "search",
      badge: "날씨 영향 없음",
      notes: ["전시 종료일과 회차 시간을 최종 확인하세요", "한 장소에서 오래 머물러 이동 피로가 적어요"],
      categories: ["birthday", "anniversary", "date", "proposal", "thanks", "special"],
      query: "데이트 전시 예매",
      reason: "바로 식사를 시작하는 것보다 함께 본 장면이 생겨 이후 대화가 자연스러워요.",
      venueType: "indoor",
    },
    {
      key: "one-day-class",
      title: "함께 완성하는 원데이 클래스",
      subtitle: "향·도자기·드로잉 중 취향에 맞게",
      price: 78000,
      durationMinutes: 110,
      provider: "원데이 클래스 탐색",
      handoffKind: "search",
      badge: "기억에 남는 선택",
      notes: ["2인 동시 예약 가능 여부를 확인하세요", "완성품 수령 방식과 추가 비용을 확인하세요"],
      categories: ["birthday", "anniversary", "date", "proposal", "special"],
      query: "커플 원데이 클래스 예약",
      reason: "구경만 하는 일정이 아니라 둘만의 결과물이 남아 특별함을 높여줘요.",
      venueType: "indoor",
    },
    {
      key: "city-walk",
      title: "취향 가게를 잇는 짧은 산책",
      subtitle: "독립서점·소품숍 2곳 · 걷는 시간 30분 이내",
      price: 10000,
      durationMinutes: 80,
      provider: "동네 코스 확인",
      handoffKind: "search",
      badge: "가벼운 예산",
      notes: ["영업시간이 다른 작은 가게는 출발 전 확인하세요", "비가 오면 실내 전시 대안으로 바꾸세요"],
      categories: ["birthday", "anniversary", "date", "thanks", "special"],
      query: "데이트 독립서점 소품샵",
      reason: "정해진 프로그램보다 여유롭게 서로의 취향을 발견할 수 있어요.",
      venueType: "mixed",
      reservationRequired: false,
    },
  ],
  cafe: [
    {
      key: "spatial-garden-cafe",
      title: "정원과 빛이 있는 공간형 카페",
      subtitle: "온실·정원·개조 건축처럼 머무는 자체가 경험인 곳",
      price: 32000,
      durationMinutes: 65,
      provider: "공간과 실제 리뷰 확인",
      handoffKind: "search",
      badge: "공간이 특별해요",
      notes: ["주말 혼잡 시간과 좌석 회전 방식을 확인하세요", "맛과 서비스 평가가 기준 이하인 곳은 제외해요"],
      categories: ["birthday", "anniversary", "date", "proposal", "thanks", "special"],
      query: "정원 온실 한옥 개조 건축 공간 특별한 로컬 카페",
      reason: "단순히 쉬는 카페가 아니라 앞선 경험의 여운을 나눌 수 있는 한 장면으로 골라요.",
      venueType: "indoor",
      reservationRequired: false,
    },
    {
      key: "quiet-dessert",
      title: "창가가 있는 디저트 카페",
      subtitle: "식사 전 쉬어가는 60분 · 대화 중심",
      price: 28000,
      durationMinutes: 60,
      provider: "가까운 카페 확인",
      handoffKind: "search",
      badge: "동선 완충",
      notes: ["주말에는 대기 여부를 확인하세요", "식사와 겹치지 않게 디저트는 하나만 나눠도 충분해요"],
      categories: ["birthday", "anniversary", "date", "proposal", "thanks", "special"],
      query: "조용한 디저트 카페",
      reason: "첫 일정의 여운을 나누고 저녁 전 호흡을 고르는 시간이에요.",
      venueType: "indoor",
      reservationRequired: false,
    },
    {
      key: "roastery",
      title: "향 좋은 로스터리의 바 좌석",
      subtitle: "커피 취향을 고르는 짧은 경험",
      price: 18000,
      durationMinutes: 50,
      provider: "로스터리 위치 확인",
      handoffKind: "search",
      badge: "예산 절약",
      notes: ["카페인을 피하면 디카페인 가능 여부를 확인하세요", "혼잡하면 테이크아웃 후 다음 장소로 이동하세요"],
      categories: ["birthday", "anniversary", "date", "thanks", "special"],
      query: "분위기 좋은 로스터리 카페",
      reason: "비용은 가볍지만 함께 취향을 고르는 작은 상호작용이 생겨요.",
      venueType: "indoor",
      reservationRequired: false,
    },
  ],
  meal: [
    {
      key: "memorable-local-dining",
      title: "공간이 기억에 남는 로컬 다이닝",
      subtitle: "정원·한옥·독특한 건축과 음식 품질을 함께 보는 저녁",
      price: 88000,
      durationMinutes: 105,
      provider: "공식 예약과 실제 리뷰 확인",
      handoffKind: "search",
      badge: "하루의 중심",
      notes: ["음식 평점과 최근 서비스 리뷰를 함께 확인하세요", "조용한 좌석 또는 기념일 요청 가능 여부를 확인하세요"],
      categories: ["birthday", "anniversary", "date", "proposal", "thanks", "special"],
      query: "정원 한옥 독특한 건축 분위기 좋은 로컬 다이닝 리뷰 좋은",
      reason: "식사도 이동 중 끼워 넣는 항목이 아니라 공간과 맛이 함께 기억되는 중심 장면으로 골라요.",
      venueType: "indoor",
    },
    {
      key: "window-italian",
      title: "대화하기 좋은 창가 이탈리안",
      subtitle: "조도 낮은 2인석 · 저녁 코스 대신 단품 구성",
      price: 72000,
      durationMinutes: 100,
      provider: "네이버 예약에서 확인",
      handoffKind: "search",
      badge: "분위기 우선",
      notes: ["창가 또는 안쪽 조용한 좌석을 요청하세요", "당일이면 18시 이전 시간이 성공 확률이 높아요"],
      categories: ["birthday", "anniversary", "date", "proposal"],
      query: "기념일 분위기 좋은 이탈리안 예약",
      reason: "하루의 중심이 되는 식사라 대화하기 좋은 좌석과 실패가 적은 메뉴 구성을 우선했어요.",
    },
    {
      key: "warm-korean",
      title: "정갈한 한식 다이닝",
      subtitle: "호불호가 적고 편안한 식사 · 2인 기준",
      price: 64000,
      durationMinutes: 90,
      provider: "네이버 예약에서 확인",
      handoffKind: "search",
      badge: "실패 적음",
      notes: ["부모님·차분한 데이트에 잘 맞아요", "알레르기와 못 먹는 음식을 예약 메모에 남기세요"],
      categories: ["birthday", "anniversary", "thanks"],
      query: "조용한 한식 다이닝 예약",
      reason: "과한 연출보다 편안한 대화를 원할 때 만족도가 안정적인 선택이에요.",
    },
    {
      key: "casual-date",
      title: "캐주얼 와인바 & 플레이트",
      subtitle: "부담 없는 분위기 · 논알코올 선택 가능",
      price: 56000,
      durationMinutes: 90,
      provider: "네이버 예약에서 확인",
      handoffKind: "search",
      badge: "당일 대안 많음",
      notes: ["술을 마시지 않아도 되는 곳을 우선 확인해요", "바 좌석보다 테이블 좌석을 요청하세요"],
      categories: ["birthday", "date", "anniversary"],
      query: "분위기 좋은 캐주얼 와인바 예약",
      reason: "예약 대안이 많고 분위기를 놓치지 않아 급한 일정에도 균형이 좋아요.",
    },
  ],
  view: [
    {
      key: "light-night-finale",
      title: "빛으로 완성되는 밤의 하이라이트",
      subtitle: "야간 미디어아트·특별 경관·시즌 프로그램 우선",
      price: 30000,
      durationMinutes: 75,
      provider: "오늘 운영하는 야간 경험 확인",
      handoffKind: "search",
      badge: "강한 마무리",
      notes: ["방문 날짜의 운영 여부와 종료 시간을 확인하세요", "실외라면 날씨와 귀가 동선을 함께 확인하세요"],
      categories: ["birthday", "anniversary", "date", "proposal", "thanks", "special"],
      query: "야간 미디어아트 빛 축제 특별 야경 기간 한정",
      reason: "하루가 끝난 뒤에도 가장 먼저 떠오를 수 있는 강한 장면을 마지막에 배치했어요.",
      venueType: "mixed",
    },
    {
      key: "city-lights",
      title: "도시 불빛을 보는 마지막 40분",
      subtitle: "식사 장소에서 대중교통 20분 안쪽",
      price: 0,
      durationMinutes: 40,
      provider: "가까운 야경 명소 확인",
      handoffKind: "search",
      badge: "하루의 피날레",
      notes: ["일몰과 운영 종료 시간을 확인하세요", "귀가 동선에서 크게 벗어나지 않는 곳을 고르세요"],
      categories: ["birthday", "anniversary", "date", "proposal", "special"],
      query: "대중교통 야경 데이트",
      reason: "새 일정을 무리하게 더하기보다 하루를 기억하게 만드는 선명한 마지막 장면이에요.",
      venueType: "outdoor",
      reservationRequired: false,
    },
    {
      key: "indoor-observatory",
      title: "실내 전망 라운지에서 야경",
      subtitle: "날씨 걱정 없이 앉아서 보는 도심 뷰",
      price: 36000,
      durationMinutes: 55,
      provider: "전망대·라운지 확인",
      handoffKind: "search",
      badge: "실내 피날레",
      notes: ["입장권 또는 좌석 예약이 필요한지 확인하세요", "음료 최소 주문 금액이 있는지 확인하세요"],
      categories: ["birthday", "anniversary", "date", "proposal", "special"],
      query: "실내 야경 전망대 라운지 예약",
      reason: "비나 추위가 있어도 마지막 장면의 분위기를 지킬 수 있어요.",
      venueType: "indoor",
      reservationRequired: true,
    },
    {
      key: "night-drive-view",
      title: "차로 이어가는 조용한 전망 포인트",
      subtitle: "주차 가능한 곳을 우선 탐색",
      price: 12000,
      durationMinutes: 45,
      provider: "주차 가능한 전망지 확인",
      handoffKind: "search",
      badge: "차량 이동",
      notes: ["야간 주차 가능 시간과 요금을 확인하세요", "음주 계획이 있다면 선택하지 마세요"],
      categories: ["birthday", "anniversary", "date", "proposal", "special"],
      query: "주차 가능한 서울 야경 명소",
      reason: "차량이 있을 때 이동 부담을 줄이고 둘만의 대화를 이어가기 좋아요.",
      venueType: "outdoor",
      reservationRequired: false,
    },
  ],
  lodging: [
    {
      key: "local-boutique-stay",
      title: "동선 한가운데 있는 감성 숙소",
      subtitle: "체크인 15:00 · 청결·후기·방음·이동 위치를 함께 확인",
      price: 180000,
      durationMinutes: 960,
      provider: "공식 숙소 예약과 실제 후기 확인",
      handoffKind: "search",
      badge: "숙박 동선 중심",
      notes: ["체크인·체크아웃 시간과 취소 규정을 결제 전에 확인해요", "사진보다 최근 청결·방음 리뷰와 실제 객실 타입을 우선 확인해요"],
      categories: ["birthday", "anniversary", "date", "proposal", "thanks", "special"],
      query: "감성 부티크 호텔 숙소 후기 좋은 청결 위치 좋은",
      reason: "낮 일정과 저녁 사이에 체크인할 수 있고 다음 날 출발도 무리 없는 위치를 우선해요.",
      venueType: "indoor",
      reservationRequired: true,
    },
    {
      key: "view-stay",
      title: "전망이 기억에 남는 조용한 숙소",
      subtitle: "야경·바다·정원 전망 중 지역에 맞는 실제 객실 확인",
      price: 240000,
      durationMinutes: 960,
      provider: "공식 숙소 예약과 실제 후기 확인",
      handoffKind: "search",
      badge: "여행의 하이라이트",
      notes: ["전망 객실이 실제 예약 객실명에 포함되는지 확인해요", "주말 추가요금과 환불 가능 기한을 함께 확인해요"],
      categories: ["birthday", "anniversary", "date", "proposal", "thanks", "special"],
      query: "전망 좋은 감성 호텔 펜션 후기 좋은 조용한 숙소",
      reason: "숙소를 잠만 자는 곳이 아니라 여행에서 가장 오래 머무는 장면으로 봤어요.",
      venueType: "indoor",
      reservationRequired: true,
    },
    {
      key: "practical-stay",
      title: "위치와 청결이 검증된 로컬 스테이",
      subtitle: "환승과 짐 이동을 줄이는 위치 · 최근 후기 우선",
      price: 130000,
      durationMinutes: 960,
      provider: "공식 숙소 예약과 실제 후기 확인",
      handoffKind: "search",
      badge: "예산 균형",
      notes: ["최종 가격에 세금과 청소비가 포함됐는지 확인해요", "늦은 체크인 가능 여부를 결제 전에 확인해요"],
      categories: ["birthday", "anniversary", "date", "proposal", "thanks", "special"],
      query: "위치 좋은 청결한 호텔 숙소 최근 후기 좋은",
      reason: "숙박비는 줄이면서 이동 피로와 청결 실패 가능성을 낮추는 선택이에요.",
      venueType: "indoor",
      reservationRequired: true,
    },
  ],
  cake: [
    {
      key: "mini-lettering",
      title: "당일 픽업 미니 레터링 케이크",
      subtitle: "2인용 · 짧은 문구 12자까지",
      price: 29000,
      durationMinutes: 15,
      provider: "주변 케이크숍 찾기",
      handoffKind: "search",
      badge: "당일 문의",
      notes: ["주문 전 당일 제작 가능 여부를 꼭 확인하세요", "문구 예시: 오늘도 네 편이야"],
      categories: ["birthday", "anniversary", "proposal", "thanks"],
      query: "당일 레터링 케이크",
    },
    {
      key: "bakery-cake",
      title: "예약 없이 픽업 가능한 홀케이크",
      subtitle: "재고 확인 후 바로 픽업 · 초 포함",
      price: 24000,
      durationMinutes: 10,
      provider: "가까운 베이커리 찾기",
      handoffKind: "search",
      badge: "가장 빠름",
      notes: ["레터링 대신 손글씨 카드로 마음을 보완해요", "출발 전 지점 재고를 확인하세요"],
      categories: ["birthday", "anniversary", "date", "thanks"],
      query: "홀케이크 당일 픽업",
    },
  ],
  flower: [
    {
      key: "season-bouquet",
      title: "계절 꽃다발 M",
      subtitle: "과한 포장 없이 따뜻한 색감으로",
      price: 38000,
      durationMinutes: 15,
      provider: "주변 꽃집 찾기",
      handoffKind: "search",
      badge: "사진 확인 권장",
      notes: ["받는 분이 좋아하는 색을 주문 메모에 남기세요", "꽃 종류보다 전체 색감을 지정하면 실패가 적어요"],
      categories: ["birthday", "anniversary", "date", "proposal", "thanks"],
      query: "꽃다발 당일 픽업",
    },
    {
      key: "single-flower",
      title: "한 송이 포장 + 메시지 카드",
      subtitle: "부담은 줄이고 기억에는 남게",
      price: 15000,
      durationMinutes: 10,
      provider: "주변 꽃집 찾기",
      handoffKind: "search",
      badge: "예산 절약",
      notes: ["메인 선물이 있을 때 균형이 좋아요", "계절에 따라 가장 싱싱한 꽃으로 요청하세요"],
      categories: ["birthday", "anniversary", "date", "thanks"],
      query: "꽃 한송이 포장",
    },
  ],
  gift: [
    {
      key: "warm-care",
      title: "향이 은은한 핸드케어 세트",
      subtitle: "취향을 많이 타지 않는 실용 선물",
      price: 32000,
      durationMinutes: 5,
      provider: "카카오톡 선물하기",
      handoffKind: "gift",
      badge: "바로 선물 가능",
      notes: ["향에 민감하다면 무향 옵션을 고르세요", "배송 선물은 식사 전에 먼저 보내도 좋아요"],
      categories: ["birthday", "anniversary", "date", "thanks"],
      query: "핸드케어 선물세트",
    },
    {
      key: "tea-set",
      title: "프리미엄 티 & 디저트 세트",
      subtitle: "연령과 취향 부담이 적은 감사 선물",
      price: 27000,
      durationMinutes: 5,
      provider: "카카오톡 선물하기",
      handoffKind: "gift",
      badge: "감사 선물",
      notes: ["카페인을 피한다면 허브티 구성을 골라요", "짧은 메시지를 반드시 함께 보내세요"],
      categories: ["birthday", "thanks", "anniversary"],
      query: "프리미엄 티 선물세트",
    },
    {
      key: "photo-ticket",
      title: "둘만의 사진 인화 + 작은 액자",
      subtitle: "가격보다 기억을 남기는 선택",
      price: 22000,
      durationMinutes: 25,
      provider: "주변 즉석 사진관 찾기",
      handoffKind: "search",
      badge: "마음 중심",
      notes: ["가장 최근 사진보다 함께한 의미가 큰 사진이 좋아요", "뒷면에 날짜와 한 문장을 적어주세요"],
      categories: ["birthday", "anniversary", "proposal", "date"],
      query: "사진 즉석 인화 액자",
    },
  ],
  moment: [
    {
      key: "three-line-card",
      title: "세 문장 손글씨 카드",
      subtitle: "고마웠던 일 · 좋아하는 이유 · 다음 약속",
      price: 3000,
      durationMinutes: 12,
      provider: "내가 직접 준비",
      handoffKind: "self",
      badge: "가장 기억에 남음",
      notes: ["길게 쓰기보다 구체적인 한 장면을 적으세요", "선물 봉투 안보다 식사 후 직접 읽어주는 편이 좋아요"],
      categories: ["birthday", "anniversary", "date", "proposal", "thanks"],
    },
    {
      key: "memory-walk",
      title: "식사 후 20분 추억 산책",
      subtitle: "사진 한 장과 다음 데이트 약속 남기기",
      price: 0,
      durationMinutes: 20,
      provider: "내가 직접 준비",
      handoffKind: "self",
      badge: "비용 0원",
      notes: ["이동이 길어지지 않도록 식당 근처 동선을 택해요", "사진 촬영을 목표로 만들면 어색하지 않아요"],
      categories: ["birthday", "anniversary", "date", "thanks"],
    },
  ],
};

function optionHref(entry: CatalogEntry, situation: ParsedSituation, category: PlanCategory): string {
  if (entry.handoffKind === "self") return "#self";
  if (entry.handoffKind === "gift") return giftSearch(entry.query ?? entry.title);
  return encodedSearch(category, situation.region);
}

export function getOptions(category: PlanCategory, situation: ParsedSituation): PlanOption[] {
  const matching = entries[category].filter((entry) => entry.categories.includes(situation.occasion));
  const pool = matching.length > 0 ? matching : entries[category];
  return pool.map((entry, index) => {
    const option: PlanOption = {
      id: `${category}-${entry.key}`,
      title: entry.title,
      subtitle: entry.subtitle,
      price: entry.price,
      durationMinutes: entry.durationMinutes,
      provider: entry.provider,
      handoffKind: entry.handoffKind,
      href: optionHref(entry, situation, category),
      badge: entry.badge,
      notes: entry.notes,
      // 실제 가게가 아직 안 붙은 상태를 "탐색 중"처럼 보이게 두면 진짜 장소로 오해한다.
      location: entry.location ?? (entry.handoffKind === "gift" ? "온라인 · 바로 전송" : entry.handoffKind === "self" ? "직접 준비" : `${situation.region} · 실제 가게 아직 못 찾음`),
      imageUrl: entry.imageUrl ?? visuals[category].imageUrl,
      referenceImageUrl: visuals[category].imageUrl,
      imageAlt: entry.imageAlt ?? visuals[category].imageAlt,
      reason: entry.reason ?? `${situation.occasionLabel}의 흐름과 ${situation.budget.toLocaleString("ko-KR")}원 예산을 함께 고려한 선택이에요.`,
      venueType: entry.venueType ?? visuals[category].venueType,
      reservationRequired: entry.reservationRequired ?? visuals[category].reservationRequired,
    };
    return { ...option, experience: buildExperienceProfile(option, category, situation, { index, total: pool.length }) };
  });
}
