export const TS_STRINGS = {
  brand: "토스샵인사이트",
  tagline: "토스쇼핑 셀러를 위한 랭킹·키워드·경쟁사·정산 도구",
  navHome: "홈",
  navRankings: "랭킹·가격",
  navKeywords: "키워드",
  navCompetitors: "경쟁사",
  navSettlements: "정산",
  navDashboard: "대시보드",
  navLogin: "로그인",
  navLogout: "로그아웃",
  ctaStart: "무료로 시작하기",
  ctaDemo: "데모 계정으로 체험",
  heroTitle: "토스쇼핑 셀러 데이터를 한눈에",
  heroSubtitle: "베스트셀러 랭킹 추적, 키워드 분석, 경쟁사 알림, 정산 대조까지 — 셀러 운영에 필요한 도구를 모았습니다.",
  demoEmail: "demo@tossshop.local",
  demoPassword: "demo1234",
  footer: "토스샵인사이트 — 토스쇼핑 공식 도구가 아닌 독립 서비스입니다.",
} as const;
