import { applyPriorityAnalysisToDraft } from "../apply-service-priority";
import { normalizeLossCategory, inferLossCategoryFromText } from "../loss-category";
import type { JobPriority } from "../types";
import type { ShopVertical } from "../shop-vertical.js";
import { getVerticalConfig } from "../vertical-config.js";
import type { FieldConfidence, IntakeDraft } from "./types";

export type IntakeExtractionResult = {
  draft: IntakeDraft;
  confidence: FieldConfidence;
};

const ASR_DISCLAIMER =
  "IMPORTANT: This transcript was generated by telephone speech recognition and may contain misheard words, phonetic substitutions, or missing syllables. Use contextual reasoning to interpret garbled input — for example, '482 Elm' likely means an address, 'sewidge' means sewage, 'moldy' means mold damage. Do not reject ambiguous input; infer the most probable meaning from context.\n\n";

/** Build the extraction system prompt for a given vertical. */
export function buildExtractionPrompt(vertical: ShopVertical): string {
  if (vertical === "restoration") return SYSTEM_PROMPT;
  const cfg = getVerticalConfig(vertical);

  const optionalFieldRules = cfg.optionalIntakeFields
    .map((f) => {
      if (f.type === "choice" && f.choices) {
        return `- ${f.key}: one of [${f.choices.join(" | ")}] if mentioned, else ""`;
      }
      if (f.type === "checkbox") {
        return `- ${f.key}: true or false if mentioned either way, else omit`;
      }
      return `- ${f.key}: ${f.label} if mentioned, else ""`;
    })
    .join("\n");

  const optionalFieldJsonKeys = cfg.optionalIntakeFields
    .map((f) => `  "${f.key}": ${f.type === "checkbox" ? "false" : '""'}`)
    .join(",\n");

  return `${ASR_DISCLAIMER}You are a ${cfg.label} after-hours intake assistant for a US home services company.
Extract structured fields from call notes. Never confirm dispatch or assign crews without shop approval.

Rules:
- customerName: caller's name only
- address: full property street address with city/state when possible
- serviceLocation: where the issue is (usually same as address)
- issueType: short label describing the ${cfg.shortLabel} issue (e.g. ${cfg.issueExamples.slice(0, 3).map((e) => `"${e}"`).join(", ")})
- symptom: dispatcher-friendly label
- lossCategory: use "other" for non-restoration calls, or best match: water | fire | mold | sewage_cat3 | commercial | inspection | other
- arrivalWindow: customer preference ONLY or "Pending dispatch review" — never confirmed ETA
- Do NOT set priority here (classified separately)
- phone: IGNORE spoken phone numbers; always return "USE_CALLER_ID"
- confidence: 0-100 per field for customerName, address, serviceLocation, issueType

Also extract these ${cfg.shortLabel}-specific fields if mentioned (leave blank/omit if not mentioned —
the caller will be asked about anything still missing later in the call):
${optionalFieldRules || "- (none specific to this trade)"}

Respond JSON only:
{
  "customerName": string,
  "address": string,
  "serviceLocation": string,
  "issueType": string,
  "symptom": string,
  "lossCategory": string,
${optionalFieldJsonKeys ? `${optionalFieldJsonKeys},\n` : ""}  "arrivalWindow": string,
  "dispatchNotes": string,
  "jobberPasteBlock": string,
  "confidence": {
    "customerName": number,
    "address": number,
    "serviceLocation": number,
    "issueType": number
  }
}`;
}

/** Vertical-aware extraction — uses the right prompt for the shop's trade. */
export async function extractIntakeFromSpeechForVertical(
  vertical: ShopVertical,
  speech: string,
  menuPriority: JobPriority | null,
): Promise<IntakeExtractionResult> {
  return extractIntakeFromSpeechWithPrompt(
    buildExtractionPrompt(vertical),
    speech,
    menuPriority,
  );
}

const SYSTEM_PROMPT = `${ASR_DISCLAIMER}You are a restoration after-hours intake assistant for US water, fire, and mold companies.
Extract structured fields from call notes. Never confirm dispatch or assign crews without shop approval.

Rules:
- customerName: caller's name only
- address: full property street address with city/state when possible
- serviceLocation: where loss occurred (usually same as address; if unclear, copy address)
- issueType: short label (e.g. "Basement flooding", "Fire damage", "Mold growth", "Sewage backup")
- symptom: dispatcher label (Water loss, Fire/smoke, Mold, Sewage, Inspection)
- lossCategory: water | fire | mold | sewage_cat3 | commercial | inspection | other
- insuranceCarrier: carrier name if mentioned, else empty string
- insuranceClaimNumber: claim # if mentioned, else empty string
- waterSource: e.g. supply line, appliance, roof leak — if water loss and mentioned
- activeLoss: true if damage is actively spreading now, false if the caller says it's not, omit if not mentioned
- severity: one of "Minor" | "Moderate" | "Severe" if the caller describes how bad the damage is, else omit
- arrivalWindow: customer preference ONLY or "Pending dispatch review" — never confirmed ETA
- Do NOT set priority here (classified separately from full transcript)
- phone: IGNORE spoken phone numbers; always return "USE_CALLER_ID"
- confidence: 0-100 per field for customerName, address, serviceLocation, issueType

Respond JSON only:
{
  "customerName": string,
  "address": string,
  "serviceLocation": string,
  "issueType": string,
  "symptom": string,
  "lossCategory": string,
  "insuranceCarrier": string,
  "insuranceClaimNumber": string,
  "waterSource": string,
  "activeLoss": boolean,
  "severity": string,
  "arrivalWindow": string,
  "dispatchNotes": string,
  "jobberPasteBlock": string,
  "confidence": {
    "customerName": number,
    "address": number,
    "serviceLocation": number,
    "issueType": number
  }
}`;

function clampConfidence(n: unknown): number {
  const v = typeof n === "number" ? n : Number(n);
  if (!Number.isFinite(v)) return 50;
  return Math.min(100, Math.max(0, Math.round(v)));
}

function asString(value: unknown, fallback = "Unknown"): string {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

/** Returns undefined (not mentioned) rather than a fallback, so callers can tell
 * "not mentioned yet" apart from an explicit empty answer. */
function asOptionalString(value: unknown): string | undefined {
  return typeof value === "string" && value.trim() ? value.trim() : undefined;
}

/** Tri-state boolean: true/false only when the model actually reported one, else
 * undefined ("not mentioned" — distinct from an explicit "no"). */
function asOptionalBool(value: unknown): boolean | undefined {
  return typeof value === "boolean" ? value : undefined;
}

export async function extractIntakeFromSpeech(
  speech: string,
  menuPriority: JobPriority | null,
): Promise<IntakeExtractionResult> {
  return extractIntakeFromSpeechWithPrompt(SYSTEM_PROMPT, speech, menuPriority);
}

async function extractIntakeFromSpeechWithPrompt(
  systemPrompt: string,
  speech: string,
  menuPriority: JobPriority | null,
): Promise<IntakeExtractionResult> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error("OPENAI_API_KEY_MISSING");

  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: process.env.OPENAI_MODEL ?? "gpt-4o",
      temperature: 0.1,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: `Call transcript:\n\n${speech.trim()}` },
      ],
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    console.error("[call-intake/extraction]", response.status, errText);
    throw new Error("OPENAI_REQUEST_FAILED");
  }

  const payload = (await response.json()) as {
    choices?: { message?: { content?: string } }[];
  };
  const content = payload.choices?.[0]?.message?.content;
  if (!content) throw new Error("OPENAI_EMPTY_RESPONSE");

  const data = JSON.parse(content) as Record<string, unknown>;
  const confRaw = (data.confidence ?? {}) as Record<string, unknown>;

  let draft: IntakeDraft = {
    customerName: asString(data.customerName),
    address: asString(data.address),
    serviceLocation: asString(data.serviceLocation, asString(data.address)),
    issueType: asString(data.issueType, asString(data.symptom, "Service request")),
    symptom: asString(data.symptom, "Service call"),
    priority: "P2",
    servicePriority: "normal",
    priorityReasons: [],
    prioritySource: "ai",
    arrivalWindow: asString(data.arrivalWindow, "Pending shop review"),
    dispatchNotes: asString(data.dispatchNotes),
    jobberPasteBlock: asString(data.jobberPasteBlock),
    lossCategory: normalizeLossCategory(data.lossCategory),
    insuranceCarrier: asString(data.insuranceCarrier, ""),
    insuranceClaimNumber: asString(data.insuranceClaimNumber, ""),
    waterSource: asString(data.waterSource, ""),
    // Tri-state: undefined means "not mentioned" (still needs to be asked on the call),
    // as opposed to an explicit true/false the caller already gave.
    activeLoss: asOptionalBool(data.activeLoss),
    severity: asOptionalString(data.severity),
    lastServiceYear: asOptionalString(data.lastServiceYear),
    urgency: asOptionalString(data.urgency),
  };

  if (draft.lossCategory === "other") {
    draft.lossCategory = inferLossCategoryFromText(draft.issueType, draft.symptom);
  }

  draft = await applyPriorityAnalysisToDraft(speech.trim(), draft, menuPriority);

  if (
    draft.serviceLocation.toLowerCase() === "unknown" &&
    draft.address.toLowerCase() !== "unknown"
  ) {
    draft.serviceLocation = draft.address;
  }

  const confidence: FieldConfidence = {
    customerName: clampConfidence(confRaw.customerName),
    address: clampConfidence(confRaw.address),
    serviceLocation: clampConfidence(confRaw.serviceLocation),
    issueType: clampConfidence(confRaw.issueType),
  };

  return { draft, confidence };
}
