import type { TopikQuizQuestion } from "@/topik/types";

/** 8-question placement / diagnostic — original TOPIK-format */
export const PLACEMENT_TEST: TopikQuizQuestion[] = [
  {
    id: "pl-1",
    level: 1,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「안녕하세요」의 뜻은?",
    questionVi: "「안녕하세요」 nghĩa là gì?",
    options: ["Xin chào", "Cảm ơn", "Tạm biệt", "Xin lỗi"],
    correctIndex: 0,
    explanation: "Basic greeting.",
    explanationVi: "Lời chào cơ bản.",
  },
  {
    id: "pl-2",
    level: 1,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "저는 학생___.",
    questionVi: "Điền: 저는 학생___.",
    options: ["이", "을", "입니다", "에"],
    correctIndex: 2,
    explanation: "Copula 입니다.",
    explanationVi: "Động từ liên kết 입니다.",
  },
  {
    id: "pl-3",
    level: 2,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "어제 영화를 ___.",
    questionVi: "Chia động từ quá khứ",
    options: ["봐요", "봤어요", "볼 거예요", "보세요"],
    correctIndex: 1,
    explanation: "Past tense.",
    explanationVi: "Thì quá khứ.",
  },
  {
    id: "pl-4",
    level: 2,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "남자는 무엇을 마십니까?",
    questionVi: "Người đàn ông uống gì?",
    options: ["커피", "물", "주스", "맥주"],
    correctIndex: 0,
    explanation: "He drinks coffee every morning.",
    explanationVi: "Anh ấy uống cà phê mỗi sáng.",
    listeningScript: "매일 아침 커피를 마셔요.",
    listeningScriptVi: "Mỗi sáng tôi uống cà phê.",
  },
  {
    id: "pl-5",
    level: 3,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "비가 와___ 집에 있었어요.",
    questionVi: "Điền liên từ",
    options: ["고", "서", "지만", "면"],
    correctIndex: 1,
    explanation: "-아/어서 cause.",
    explanationVi: "-아/어서 chỉ nguyên nhân.",
  },
  {
    id: "pl-6",
    level: 3,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage: "한국어를 배우는 학생이 점점 늘고 있습니다.",
    question: "무엇이 늘고 있습니까?",
    questionVi: "Điều gì đang tăng?",
    options: ["한국 음식", "한국어 학생", "한국 영화", "한국 여행"],
    correctIndex: 1,
    explanation: "Korean learners increasing.",
    explanationVi: "Số học sinh tiếng Hàn tăng.",
  },
  {
    id: "pl-7",
    level: 4,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "공부할___ 재미있어요.",
    questionVi: "Càng học càng...",
    options: ["수록", "때문에", "반면", "덕분에"],
    correctIndex: 0,
    explanation: "-(으)ㄹ수록.",
    explanationVi: "-(으)ㄹ수록 = càng ~ càng.",
  },
  {
    id: "pl-8",
    level: 5,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "힘들___ 포기하지 않겠다.",
    questionVi: "Dù khó nhưng...",
    options: ["지언정", "뿐만 아니라", "마련이다", "셈이다"],
    correctIndex: 0,
    explanation: "-(으)ㄹ지언정.",
    explanationVi: "-(으)ㄹ지언정 = dù ~ nhưng.",
  },
];
