import type { TopikQuizQuestion } from "@/topik/types";

/** Expanded bank — self-sufficient exam prep content (original, not copied past papers) */
export const TOPIK_QUESTION_BANK_EXPANDED: TopikQuizQuestion[] = [
  // Level 1
  {
    id: "ex-l1-01",
    level: 1,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「사과」는 무엇입니까?",
    questionVi: "「사과」 là gì?",
    options: ["Táo", "Cam", "Chuối", "Nho"],
    correctIndex: 0,
    explanation: "사과 means apple.",
    explanationVi: "사과 nghĩa là quả táo.",
  },
  {
    id: "ex-l1-02",
    level: 1,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「선생님」은 누구입니까?",
    questionVi: "「선생님」 là ai?",
    options: ["Học sinh", "Giáo viên", "Bác sĩ", "Đầu bếp"],
    correctIndex: 1,
    explanation: "선생님 means teacher.",
    explanationVi: "선생님 nghĩa là giáo viên.",
  },
  {
    id: "ex-l1-03",
    level: 1,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "이것___ 책입니다.",
    questionVi: "Điền: 이것___ 책입니다.",
    options: ["은", "를", "에", "와"],
    correctIndex: 0,
    explanation: "Topic marker 은/는.",
    explanationVi: "Trợ từ chủ ngữ 은/는.",
  },
  {
    id: "ex-l1-l01",
    level: 1,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "여자는 무엇을 먹습니까?",
    questionVi: "Người phụ nữ ăn gì?",
    options: ["밥", "빵", "과일", "국"],
    correctIndex: 0,
    explanation: "She eats rice for lunch.",
    explanationVi: "Cô ấy ăn cơm trưa.",
    listeningScript: "점심에 밥을 먹어요.",
    listeningScriptVi: "Buổi trưa tôi ăn cơm.",
  },

  // Level 2
  {
    id: "ex-l2-01",
    level: 2,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "한국어를 배우___ 싶어요.",
    questionVi: "Chia: 한국어를 배우___ 싶어요.",
    options: ["고", "러", "면", "서"],
    correctIndex: 1,
    explanation: "-(으)러 for purpose of going to do.",
    explanationVi: "-(으)러 = để (mục đích).",
  },
  {
    id: "ex-l2-02",
    level: 2,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「시간」의 뜻은?",
    questionVi: "「시간」 nghĩa là gì?",
    options: ["Tiền", "Thời gian", "Chỗ", "Ngày"],
    correctIndex: 1,
    explanation: "시간 means time.",
    explanationVi: "시간 nghĩa là thời gian.",
  },
  {
    id: "ex-l2-r01",
    level: 2,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage: "민수 씨는 매일 한국어를 공부합니다. 토요일에는 친구와 같이 카페에서 공부합니다.",
    question: "토요일에 민수 씨는 어디에서 공부합니까?",
    questionVi: "Thứ Bảy Min-su học ở đâu?",
    options: ["학교", "카페", "도서관", "집"],
    correctIndex: 1,
    explanation: "At cafe on Saturday.",
    explanationVi: "Thứ Bảy học ở quán cà phê.",
  },

  // Level 3
  {
    id: "ex-l3-01",
    level: 3,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "한국에 온 ___ 3년이 됐어요.",
    questionVi: "Điền: 한국에 온 ___ 3년이 됐어요.",
    options: ["지", "고", "면", "서"],
    correctIndex: 0,
    explanation: "-(으)ㄴ 지 duration.",
    explanationVi: "-(으)ㄴ 지 = đã ~ bao lâu.",
  },
  {
    id: "ex-l3-02",
    level: 3,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「준비」의 뜻은?",
    questionVi: "「준비」 nghĩa là gì?",
    options: ["Kết quả", "Chuẩn bị", "Thất bại", "Bắt đầu"],
    correctIndex: 1,
    explanation: "준비 means preparation.",
    explanationVi: "준비 nghĩa là chuẩn bị.",
  },
  {
    id: "ex-l3-l01",
    level: 3,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "남자의 직업은?",
    questionVi: "Nghề của người đàn ông?",
    options: ["학생", "회사원", "선생님", "의사"],
    correctIndex: 1,
    explanation: "He works at a company.",
    explanationVi: "Anh ấy làm ở công ty.",
    listeningScript: "저는 회사원입니다. 서울에서 일해요.",
    listeningScriptVi: "Tôi là nhân viên công ty. Làm việc ở Seoul.",
  },

  // Level 4
  {
    id: "ex-l4-01",
    level: 4,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "늦___ 택시를 탔어요.",
    questionVi: "Vì muộn nên đi taxi",
    options: ["어서", "지만", "으면", "더니"],
    correctIndex: 0,
    explanation: "-아/어서 cause.",
    explanationVi: "-아/어서 = vì.",
  },
  {
    id: "ex-l4-r01",
    level: 4,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage: "스마트폰 사용 시간이 늘면서 눈 건강에 대한 걱정도 커지고 있다. 전문가들은 20-20-20 법칙을 권장한다.",
    question: "전문가들이 권장하는 것은?",
    questionVi: "Chuyên gia khuyên gì?",
    options: ["스마트폰 금지", "20-20-20 법칙", "안경 착용", "운동"],
    correctIndex: 1,
    explanation: "20-20-20 rule recommended.",
    explanationVi: "Khuyên quy tắc 20-20-20.",
  },

  // Level 5
  {
    id: "ex-l5-01",
    level: 5,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "그의 주장은 타당성이 ___.",
    questionVi: "Luận điểm có tính thuyết phục",
    options: ["있다", "없다", "많다", "적다"],
    correctIndex: 0,
    explanation: "타당성이 있다 = has validity.",
    explanationVi: "Có tính hợp lý.",
  },
  {
    id: "ex-l5-r01",
    level: 5,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage: "글로벌화로 인해 문화 교류가 활발해졌지만, 문화적 갈등도 심화되고 있다.",
    question: "글의 주제는?",
    questionVi: "Chủ đề bài viết?",
    options: ["경제 성장", "문화 교류와 갈등", "기술 발전", "교육 제도"],
    correctIndex: 1,
    explanation: "Cultural exchange and conflict.",
    explanationVi: "Giao lưu và xung đột văn hóa.",
  },

  // Level 6
  {
    id: "ex-l6-01",
    level: 6,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "성공하___ 실패하___ 노력은 필요하다.",
    questionVi: "Dù thành công hay thất bại",
    options: ["든", "면", "고", "서"],
    correctIndex: 0,
    explanation: "-(으)든 contrast pair.",
    explanationVi: "-(으)든 = dù ~ hay ~.",
  },

  // EPS-style
  {
    id: "ex-eps-01",
    level: 2,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「공장」은 어디입니까?",
    questionVi: "「공장」 là gì? (EPS)",
    options: ["Nhà máy", "Nông trại", "Cửa hàng", "Bệnh viện"],
    correctIndex: 0,
    explanation: "공장 means factory.",
    explanationVi: "공장 nghĩa là nhà máy — từ vựng EPS.",
  },
  {
    id: "ex-eps-02",
    level: 2,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「안전」의 뜻은?",
    questionVi: "「안전」 nghĩa là gì? (EPS)",
    options: ["An toàn", "Nguy hiểm", "Nhanh", "Chậm"],
    correctIndex: 0,
    explanation: "안전 means safety.",
    explanationVi: "안전 nghĩa là an toàn.",
  },
];
