import type { TopikQuizQuestion } from "@/topik/types";

/**
 * Original TOPIK-format practice questions.
 * Not copied from copyrighted past exam papers — inspired by official syllabus.
 */
export const TOPIK_QUESTION_BANK: TopikQuizQuestion[] = [
  // ── TOPIK I · Level 1 ──
  {
    id: "l1-v-01",
    level: 1,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「물」의 뜻은?",
    questionVi: "「물」 nghĩa là gì?",
    options: ["Nước", "Lửa", "Gió", "Đất"],
    correctIndex: 0,
    explanation: "물 means water.",
    explanationVi: "물 nghĩa là nước.",
  },
  {
    id: "l1-v-02",
    level: 1,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「학교」는 무엇입니까?",
    questionVi: "「학교」 là gì?",
    options: ["Bệnh viện", "Trường học", "Siêu thị", "Ngân hàng"],
    correctIndex: 1,
    explanation: "학교 means school.",
    explanationVi: "학교 nghĩa là trường học.",
  },
  {
    id: "l1-g-01",
    level: 1,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "저___ 민수입니다.",
    questionVi: "Điền: 저___ 민수입니다. (Tôi là Min-su)",
    options: ["는", "를", "에", "와"],
    correctIndex: 0,
    explanation: "는/은 marks the topic.",
    explanationVi: "는/은 là trợ từ chủ ngữ.",
  },
  {
    id: "l1-g-02",
    level: 1,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "사과___ 먹어요.",
    questionVi: "Điền: 사과___ 먹어요. (Ăn táo)",
    options: ["를", "에서", "에게", "와"],
    correctIndex: 0,
    explanation: "를/을 marks the object.",
    explanationVi: "를/을 là trợ từ tân ngữ.",
  },
  {
    id: "l1-l-01",
    level: 1,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "대화를 듣고 알맞은 그림을 고르십시오.",
    questionVi: "Nghe hội thoại và chọn hình đúng.",
    options: ["커피를 마신다", "책을 읽는다", "음악을 듣는다", "운동을 한다"],
    correctIndex: 0,
    explanation: "The speaker says they drink coffee every morning.",
    explanationVi: "Người nói uống cà phê mỗi sáng.",
    listeningScript: "A: 아침에 뭐 해요?\nB: 커피를 마셔요.",
    listeningScriptVi: "A: Sáng làm gì?\nB: Uống cà phê.",
  },
  {
    id: "l1-r-01",
    level: 1,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage: "저는 베트남 사람입니다. 한국어를 공부합니다.",
    question: "저는 어느 나라 사람입니까?",
    questionVi: "Người nói đến từ nước nào?",
    options: ["한국", "베트남", "중국", "일본"],
    correctIndex: 1,
    explanation: "The passage says they are Vietnamese.",
    explanationVi: "Đoạn văn nói người nói là người Việt Nam.",
  },

  // ── TOPIK I · Level 2 ──
  {
    id: "l2-g-01",
    level: 2,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "어제 영화를 ___.",
    questionVi: "Chia động từ: 어제 영화를 ___.",
    options: ["봐요", "봤어요", "볼 거예요", "보세요"],
    correctIndex: 1,
    explanation: "Past tense of 보다 is 봤어요.",
    explanationVi: "Thì quá khứ của 보다 là 봤어요.",
  },
  {
    id: "l2-g-02",
    level: 2,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "학교___ 공부해요.",
    questionVi: "Điền trợ từ: 학교___ 공부해요.",
    options: ["을", "에서", "에게", "와"],
    correctIndex: 1,
    explanation: "에서 marks location of action.",
    explanationVi: "에서 chỉ nơi diễn ra hành động.",
  },
  {
    id: "l2-v-01",
    level: 2,
    type: "short_answer",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「친구」를 베트남어로?",
    questionVi: "Dịch 「친구」 sang tiếng Việt",
    correctAnswer: "bạn",
    explanation: "친구 means friend.",
    explanationVi: "친구 nghĩa là bạn bè.",
  },
  {
    id: "l2-l-01",
    level: 2,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "남자가 무엇을 사려고 합니까?",
    questionVi: "Người đàn ông muốn mua gì?",
    options: ["우산", "신발", "가방", "모자"],
    correctIndex: 0,
    explanation: "He says it is raining and he needs an umbrella.",
    explanationVi: "Anh ấy nói trời mưa nên cần mua ô.",
    listeningScript: "비가 와서 우산을 사려고 해요.",
    listeningScriptVi: "Vì trời mưa nên tôi định mua ô.",
  },
  {
    id: "l2-r-01",
    level: 2,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage: "토요일에 친구와 한강에 갔습니다. 날씨가 좋아서 사진을 많이 찍었습니다.",
    question: "토요일에 무엇을 했습니까?",
    questionVi: "Thứ Bảy đã làm gì?",
    options: ["영화를 봤다", "한강에 갔다", "쇼핑을 했다", "공부를 했다"],
    correctIndex: 1,
    explanation: "They went to Han River on Saturday.",
    explanationVi: "Thứ Bảy họ đã đi sông Hàn.",
  },

  // ── TOPIK II · Level 3 ──
  {
    id: "l3-g-01",
    level: 3,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "비가 와___ 집에 있었어요.",
    questionVi: "Điền liên từ: 비가 와___ 집에 있었어요.",
    options: ["고", "서", "지만", "면"],
    correctIndex: 1,
    explanation: "-아/어서 shows cause.",
    explanationVi: "-아/어서 diễn tả nguyên nhân.",
    passage: "어제 비가 많이 왔습니다.",
  },
  {
    id: "l3-g-02",
    level: 3,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "열심히 공부했___ 시험에 떨어졌어요.",
    questionVi: "Điền liên từ phù hợp",
    options: ["고", "지만", "서", "면"],
    correctIndex: 1,
    explanation: "-지만 expresses contrast.",
    explanationVi: "-지만 diễn tả tương phản.",
  },
  {
    id: "l3-v-01",
    level: 3,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「따라서」의 뜻은?",
    questionVi: "「따라서」 nghĩa là gì?",
    options: ["Tuy nhiên", "Do đó", "Hơn nữa", "Ví dụ"],
    correctIndex: 1,
    explanation: "따라서 means therefore.",
    explanationVi: "따라서 nghĩa là do đó, vì vậy.",
  },
  {
    id: "l3-l-01",
    level: 3,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "여자의 의견으로 맞는 것은?",
    questionVi: "Ý kiến đúng của người phụ nữ?",
    options: [
      "한국어 공부가 어렵다",
      "매일 조금씩 공부해야 한다",
      "시험 준비는 필요 없다",
      "회화만 연습하면 된다",
    ],
    correctIndex: 1,
    explanation: "She says studying a little every day is important.",
    explanationVi: "Cô ấy nói mỗi ngày học một chút là quan trọng.",
    listeningScript:
      "TOPIK 시험을 준비하려면 매일 조금씩 공부하는 것이 중요해요. 하루에 30분만 해도 괜찮아요.",
    listeningScriptVi:
      "Để chuẩn bị thi TOPIK, mỗi ngày học một chút là quan trọng. Chỉ 30 phút một ngày cũng được.",
  },
  {
    id: "l3-r-01",
    level: 3,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage:
      "최근 베트남에서 한국어를 배우는 학생이 늘고 있다. K-pop과 K-drama의 인기가 한국어 학습 열기를 높였다. 많은 학생들이 TOPIK 시험을 준비하고 있다.",
    question: "이 글의 중심 내용은?",
    questionVi: "Nội dung chính của đoạn văn?",
    options: [
      "베트남 음식의 인기",
      "베트남에서 한국어 학습 증가",
      "한국 드라마 줄거리",
      "TOPIK 시험 난이도",
    ],
    correctIndex: 1,
    explanation: "The passage is about increasing Korean learners in Vietnam.",
    explanationVi: "Đoạn văn nói về số người học tiếng Hàn ở Việt Nam đang tăng.",
  },
  {
    id: "l3-r-02",
    level: 3,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage: "환경을 보호하기 위해 일회용품 사용을 줄여야 한다. 작은 실천이 모이면 큰 변화를 만든다.",
    question: "글쓴이가 말하고자 하는 것은?",
    questionVi: "Tác giả muốn nói điều gì?",
    options: [
      "일회용품을 더 써야 한다",
      "환경 보호는 개인의 노력이 필요하다",
      "정부만 해결하면 된다",
      "환경 문제는 심각하지 않다",
    ],
    correctIndex: 1,
    explanation: "Individual small actions matter for environment.",
    explanationVi: "Bảo vệ môi trường cần nỗ lực cá nhân.",
  },

  // ── Level 4 ──
  {
    id: "l4-g-01",
    level: 4,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "공부할___ 재미있어요.",
    questionVi: "Điền: 공부할___ 재미있어요.",
    options: ["수록", "때문에", "반면", "덕분에"],
    correctIndex: 0,
    explanation: "-(으)ㄹ수록 = the more ~ the more.",
    explanationVi: "-(으)ㄹ수록 = càng ~ càng.",
  },
  {
    id: "l4-g-02",
    level: 4,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "선생님 ___ 합격했어요.",
    questionVi: "Điền: 선생님 ___ 합격했어요.",
    options: ["덕분에", "때문에", "반면에", "대신"],
    correctIndex: 0,
    explanation: "덕분에 = thanks to (positive).",
    explanationVi: "덕분에 = nhờ có.",
  },
  {
    id: "l4-l-01",
    level: 4,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "남자가 제안하는 것은?",
    questionVi: "Người đàn ông đề xuất gì?",
    options: [
      "시험을 포기하자",
      "스터디 그룹을 만들자",
      "선생님을 바꾸자",
      "책을 더 사자",
    ],
    correctIndex: 1,
    explanation: "He suggests forming a study group.",
    explanationVi: "Anh ấy đề xuất lập nhóm học.",
    listeningScript:
      "TOPIK 시험이 한 달 남았는데, 같이 스터디 그룹을 만들어서 공부하면 어때요?",
    listeningScriptVi:
      "Còn một tháng nữa là thi TOPIK, hay mình lập nhóm học cùng nhau?",
  },
  {
    id: "l4-r-01",
    level: 4,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage:
      "디지털 시대에도 종이책을 읽는 사람들이 있다. 종이책은 눈의 피로가 적고, 집중력을 높이는 데 도움이 된다는 연구 결과가 있다. 하지만 전자책은 휴대성과 검색 기능에서 장점이 있다.",
    question: "종이책의 장점으로 언급된 것은?",
    questionVi: "Ưu điểm của sách giấy được nhắc đến?",
    options: ["휴대성", "검색 기능", "눈의 피로 감소", "저렴한 가격"],
    correctIndex: 2,
    explanation: "Less eye strain is mentioned as paper book advantage.",
    explanationVi: "Giảm mỏi mắt là ưu điểm của sách giấy.",
  },
  {
    id: "l4-w-01",
    level: 4,
    type: "multiple_choice",
    category: "writing",
    examSection: "writing",
    question: "다음 중 53번 유형(400~500자)에 적합한 주제는?",
    questionVi: "Chủ đề phù hợp dạng câu 53 IBT (400–500 ký tự)?",
    options: [
      "자기소개 (50자)",
      "한국어를 배우는 이유 (400자)",
      "날씨 묘사 (100자)",
      "메뉴 주문 (30자)",
    ],
    correctIndex: 1,
    explanation: "Q53 IBT requires 400-500 character essay.",
    explanationVi: "Câu 53 IBT yêu cầu bài luận 400–500 ký tự.",
  },

  // ── Level 5 ──
  {
    id: "l5-g-01",
    level: 5,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "가격이 싸___ 맛도 좋다.",
    questionVi: "Không những rẻ mà còn ngon",
    options: ["뿐만 아니라", "지언정", "마련이다", "셈이다"],
    correctIndex: 0,
    explanation: "-(으)ㄹ 뿐만 아니라 = not only but also.",
    explanationVi: "-(으)ㄹ 뿐만 아니라 = không những ~ mà còn.",
  },
  {
    id: "l5-g-02",
    level: 5,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "실패할 수도 있는 ___ .",
    questionVi: "Điền: 실패할 수도 있는 ___ .",
    options: ["마련이다", "셈이다", "뿐이다", "법이다"],
    correctIndex: 0,
    explanation: "마련이다 = it is natural that.",
    explanationVi: "마련이다 = đương nhiên, tất nhiên là.",
  },
  {
    id: "l5-r-01",
    level: 5,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage:
      "인공지능 기술의 발전은 교육 분야에도 큰 변화를 가져오고 있다. 개인 맞춤형 학습이 가능해졌지만, 교사의 역할이 사라지는 것은 아니다. 기술과 인간의 협력이 중요하다.",
    question: "글쓴이의 견해로 맞는 것은?",
    questionVi: "Quan điểm đúng của tác giả?",
    options: [
      "AI가 교사를 대체할 것이다",
      "AI와 교사의 협력이 필요하다",
      "AI는 교육에 부적합하다",
      "맞춤형 학습은 불가능하다",
    ],
    correctIndex: 1,
    explanation: "Cooperation between tech and humans is important.",
    explanationVi: "Hợp tác giữa công nghệ và con người là quan trọng.",
  },
  {
    id: "l5-l-01",
    level: 5,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "강연자의 주장은?",
    questionVi: "Luận điểm của diễn giả?",
    options: [
      "외국인은 한국 문화를 배울 필요가 없다",
      "언어와 문화를 함께 배워야 한다",
      "문법만 공부하면 충분하다",
      "TOPIK 점수는 중요하지 않다",
    ],
    correctIndex: 1,
    explanation: "Language and culture should be learned together.",
    explanationVi: "Nên học ngôn ngữ và văn hóa cùng lúc.",
    listeningScript:
      "한국어를 잘하려면 문법만이 아니라 문화도 함께 이해해야 합니다. 언어는 문화의 거울이니까요.",
    listeningScriptVi:
      "Muốn giỏi tiếng Hàn không chỉ học ngữ pháp mà cần hiểu văn hóa. Ngôn ngữ là gương phản ánh văn hóa.",
  },

  // ── Level 6 ──
  {
    id: "l6-g-01",
    level: 6,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "힘들___ 포기하지 않겠다.",
    questionVi: "Dù khó nhưng sẽ không bỏ cuộc",
    options: ["지언정", "뿐만 아니라", "마련이다", "셈이다"],
    correctIndex: 0,
    explanation: "-(으)ㄹ지언정 = even though.",
    explanationVi: "-(으)ㄹ지언정 = dù ~ nhưng.",
  },
  {
    id: "l6-r-01",
    level: 6,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage:
      "글로벌화 시대에 다문화 사회는 불가피한 흐름이다. 그러나 문화적 차이로 인한 갈등도 존재한다. 상호 이해와 존중이 다문화 사회의 지속 가능성을 결정한다.",
    question: "필자가 강조하는 것은?",
    questionVi: "Tác giả nhấn mạnh điều gì?",
    options: ["문화적 동질성", "상호 이해와 존중", "경제적 성장", "기술 혁신"],
    correctIndex: 1,
    explanation: "Mutual understanding and respect are emphasized.",
    explanationVi: "Nhấn mạnh sự hiểu biết và tôn trọng lẫn nhau.",
  },
  {
    id: "l6-l-01",
    level: 6,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "토론에서 두 사람이 동의하는 점은?",
    questionVi: "Hai người thống nhất điều gì?",
    options: [
      "이민 정책을 강화해야 한다",
      "다양성이 사회 발전에 기여한다",
      "전통 문화를 버려야 한다",
      "외국인 근로자를 제한해야 한다",
    ],
    correctIndex: 1,
    explanation: "Both agree diversity contributes to society.",
    explanationVi: "Cả hai đồng ý đa dạng góp phần phát triển xã hội.",
    listeningScript:
      "A: 다양한 문화가 공존하는 사회가 더 창의적이라고 생각해요.\nB: 맞아요. 다양성이 사회 발전에 기여한다는 연구도 많아요.",
    listeningScriptVi:
      "A: Tôi nghĩ xã hội đa văn hóa sáng tạo hơn.\nB: Đúng vậy. Nhiều nghiên cứu cho thấy đa dạng góp phần phát triển.",
  },

  // ── Extra mixed (legacy compatibility) ──
  {
    id: "q-l1-1",
    level: 1,
    type: "multiple_choice",
    category: "vocabulary",
    question: "「안녕하세요」의 뜻은?",
    questionVi: "「안녕하세요」 nghĩa là gì?",
    options: ["Xin chào", "Cảm ơn", "Tạm biệt", "Xin lỗi"],
    correctIndex: 0,
    explanation: "안녕하세요 is a formal greeting.",
    explanationVi: "안녕하세요 là lời chào trang trọng.",
  },
  {
    id: "q-l1-2",
    level: 1,
    type: "multiple_choice",
    category: "grammar",
    question: "저는 학생___ .",
    questionVi: "Điền trợ từ: 저는 학생___ .",
    options: ["이", "을", "에", "입니다"],
    correctIndex: 3,
    explanation: "입니다 is the copula.",
    explanationVi: "입니다 là động từ liên kết trang trọng.",
  },
  {
    id: "q-l1-3",
    level: 1,
    type: "multiple_choice",
    category: "vocabulary",
    question: "「감사합니다」의 뜻은?",
    questionVi: "「감사합니다」 nghĩa là gì?",
    options: ["Xin lỗi", "Cảm ơn", "Không sao", "Xin chào"],
    correctIndex: 1,
    explanation: "감사합니다 means thank you.",
    explanationVi: "감사합니다 nghĩa là cảm ơn.",
  },
];
