import type { TopikQuizQuestion } from "@/topik/types";

/** Additional original TOPIK-format questions — levels 1–6 */
export const TOPIK_QUESTION_BANK_EXTRA: TopikQuizQuestion[] = [
  // Level 1
  {
    id: "l1-v-03",
    level: 1,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「책」의 뜻은?",
    questionVi: "「책」 nghĩa là gì?",
    options: ["Sách", "Bút", "Bàn", "Ghế"],
    correctIndex: 0,
    explanation: "책 means book.",
    explanationVi: "책 nghĩa là sách.",
  },
  {
    id: "l1-v-04",
    level: 1,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「오늘」은 언제입니까?",
    questionVi: "「오늘」 là khi nào?",
    options: ["Hôm qua", "Hôm nay", "Ngày mai", "Tuần sau"],
    correctIndex: 1,
    explanation: "오늘 means today.",
    explanationVi: "오늘 nghĩa là hôm nay.",
  },
  {
    id: "l1-l-02",
    level: 1,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "여자는 지금 어디에 있습니까?",
    questionVi: "Người phụ nữ đang ở đâu?",
    options: ["도서관", "카페", "학교", "집"],
    correctIndex: 1,
    explanation: "She says she is at a cafe studying.",
    explanationVi: "Cô ấy nói đang ở quán cà phê học bài.",
    listeningScript: "저는 지금 카페에서 한국어를 공부하고 있어요.",
    listeningScriptVi: "Tôi đang học tiếng Hàn ở quán cà phê.",
  },
  {
    id: "l1-r-02",
    level: 1,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage: "민수는 매일 아침 7시에 일어납니다. 학교에 8시 30분에 갑니다.",
    question: "민수는 몇 시에 학교에 갑니까?",
    questionVi: "Min-su đi học lúc mấy giờ?",
    options: ["7시", "8시", "8시 30분", "9시"],
    correctIndex: 2,
    explanation: "He goes to school at 8:30.",
    explanationVi: "Anh ấy đi học lúc 8 giờ 30.",
  },

  // Level 2
  {
    id: "l2-g-03",
    level: 2,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "내일 친구를 ___.",
    questionVi: "Chia động từ: 내일 친구를 ___. (gặp bạn ngày mai)",
    options: ["만나요", "만났어요", "만날 거예요", "만나세요"],
    correctIndex: 2,
    explanation: "Future tense: -(으)ㄹ 거예요.",
    explanationVi: "Thì tương lai: -(으)ㄹ 거예요.",
  },
  {
    id: "l2-v-02",
    level: 2,
    type: "multiple_choice",
    category: "vocabulary",
    examSection: "vocabulary",
    question: "「병원」은 어디입니까?",
    questionVi: "「병원」 là gì?",
    options: ["Trường học", "Bệnh viện", "Ngân hàng", "Nhà hàng"],
    correctIndex: 1,
    explanation: "병원 means hospital.",
    explanationVi: "병원 nghĩa là bệnh viện.",
  },
  {
    id: "l2-l-02",
    level: 2,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "남자는 무엇을 하고 싶어합니까?",
    questionVi: "Người đàn ông muốn làm gì?",
    options: ["영화 보기", "한국 여행", "음식 만들기", "운동하기"],
    correctIndex: 1,
    explanation: "He wants to travel to Korea.",
    explanationVi: "Anh ấy muốn du lịch Hàn Quốc.",
    listeningScript: "내년에 한국에 여행 가고 싶어요. 한국어를 더 공부해야겠어요.",
    listeningScriptVi: "Năm sau tôi muốn du lịch Hàn Quốc. Phải học thêm tiếng Hàn.",
  },
  {
    id: "l2-r-02",
    level: 2,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage: "이 식당은 음식이 맛있지만 가격이 조금 비싸요. 그래도 많은 사람들이 찾아옵니다.",
    question: "이 식당의 특징은?",
    questionVi: "Đặc điểm của nhà hàng này?",
    options: ["음식이 맛없다", "가격이 싸다", "맛있지만 비싸다", "사람이 없다"],
    correctIndex: 2,
    explanation: "Delicious but a bit expensive.",
    explanationVi: "Ngon nhưng hơi đắt.",
  },

  // Level 3
  {
    id: "l3-g-03",
    level: 3,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "한국어를 배우___ 3년이 됐어요.",
    questionVi: "Điền: 한국어를 배우___ 3년이 됐어요.",
    options: ["고", "는", "기", "면"],
    correctIndex: 2,
    explanation: "-기 시작하다 / -기 되다 for duration.",
    explanationVi: "배우기 — dạng danh động từ chỉ hành động.",
  },
  {
    id: "l3-l-02",
    level: 3,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "대화의 내용과 같은 것은?",
    questionVi: "Nội dung đúng với hội thoại?",
    options: [
      "시험이 쉬웠다",
      "시험 준비가 부족했다",
      "시험을 포기했다",
      "시험이 없었다",
    ],
    correctIndex: 1,
    explanation: "They say preparation was insufficient.",
    explanationVi: "Họ nói chuẩn bị chưa đủ.",
    listeningScript:
      "A: TOPIK 시험 어땠어요?\nB: 준비가 부족해서 어려웠어요. 다음에는 더 열심히 해야겠어요.",
    listeningScriptVi:
      "A: Thi TOPIK thế nào?\nB: Chuẩn bị chưa đủ nên khó. Lần sau phải chăm hơn.",
  },
  {
    id: "l3-r-03",
    level: 3,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage:
      "스마트폰 사용 시간이 늘면서 독서 시간이 줄고 있다. 하지만 전자책을 이용하는 사람도 증가하고 있다.",
    question: "글의 내용으로 맞는 것은?",
    questionVi: "Nội dung đúng?",
    options: [
      "모두 책을 안 읽는다",
      "전자책 이용자가 늘고 있다",
      "스마트폰이 없어졌다",
      "독서 시간이 늘었다",
    ],
    correctIndex: 1,
    explanation: "E-book users are increasing.",
    explanationVi: "Người dùng sách điện tử đang tăng.",
  },

  // Level 4
  {
    id: "l4-g-03",
    level: 4,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "비가 올 ___ 날씨예요.",
    questionVi: "Điền: 비가 올 ___ 날씨예요. (trời sắp mưa)",
    options: ["것 같아요", "수록", "뿐이다", "마련이다"],
    correctIndex: 0,
    explanation: "-(으)ㄹ 것 같다 = seems like.",
    explanationVi: "-(으)ㄹ 것 같아요 = có vẻ như sẽ ~.",
  },
  {
    id: "l4-l-02",
    level: 4,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "여자의 계획은?",
    questionVi: "Kế hoạch của người phụ nữ?",
    options: [
      "한국에서 유학한다",
      "TOPIK 시험을 본다",
      "한국어 학원을 그만둔다",
      "베트남으로 돌아간다",
    ],
    correctIndex: 1,
    explanation: "She plans to take the TOPIK exam next month.",
    explanationVi: "Cô ấy định thi TOPIK tháng sau.",
    listeningScript: "다음 달에 TOPIK 시험을 볼 거예요. 매일 두 시간씩 공부하고 있어요.",
    listeningScriptVi: "Tháng sau tôi sẽ thi TOPIK. Mỗi ngày học hai tiếng.",
  },
  {
    id: "l4-r-02",
    level: 4,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage:
      "재택근무가 보편화되면서 출퇴근 시간은 줄었지만, 업무와 휴식의 경계가 모호해지는 문제도 생겼다.",
    question: "재택근무의 문제점은?",
    questionVi: "Vấn đề của làm việc tại nhà?",
    options: [
      "출퇴근 시간 증가",
      "업무와 휴식 구분 어려움",
      "급여 감소",
      "회사와의 단절",
    ],
    correctIndex: 1,
    explanation: "Blurred boundary between work and rest.",
    explanationVi: "Ran giới giữa công việc và nghỉ ngơi.",
  },

  // Level 5
  {
    id: "l5-g-03",
    level: 5,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "그의 주장은 설득력이 ___.",
    questionVi: "Điền: 그의 주장은 설득력이 ___. (thiếu sức thuyết phục)",
    options: ["부족하다", "넘친다", "같다", "없다"],
    correctIndex: 0,
    explanation: "부족하다 = insufficient.",
    explanationVi: "부족하다 = thiếu, không đủ.",
  },
  {
    id: "l5-r-02",
    level: 5,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage:
      "기후 변화 대응은 개인의 노력만으로는 한계가 있다. 정부와 기업의 적극적인 정책이 병행되어야 한다.",
    question: "필자의 주장은?",
    questionVi: "Luận điểm tác giả?",
    options: [
      "개인만 노력하면 된다",
      "정부·기업 정책도 필요하다",
      "기후 변화는 문제가 아니다",
      "기업이 모든 책임을 진다",
    ],
    correctIndex: 1,
    explanation: "Government and corporate policy needed too.",
    explanationVi: "Cần cả chính sách chính phủ và doanh nghiệp.",
  },

  // Level 6
  {
    id: "l6-g-02",
    level: 6,
    type: "multiple_choice",
    category: "grammar",
    examSection: "grammar",
    question: "그의 행동은 비난받을 ___ .",
    questionVi: "Điền: 그의 행동은 비난받을 ___ . (đáng bị chỉ trích)",
    options: ["만하다", "뿐이다", "셈이다", "법이다"],
    correctIndex: 0,
    explanation: "-(으)ㄹ 만하다 = worth/deserves to.",
    explanationVi: "-(으)ㄹ 만하다 = đáng ~.",
  },
  {
    id: "l6-r-02",
    level: 6,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    passage:
      "언어는 단순한 의사소통 도구가 아니라 정체성을 형성하는 핵심 요소이다. 모국어를 잃는 것은 곧 문화적 뿌리를 잃는 것과 맞닿아 있다.",
    question: "필자가 강조하는 관점은?",
    questionVi: "Quan điểm tác giả nhấn mạnh?",
    options: [
      "언어는 도구일 뿐이다",
      "언어와 정체성·문화가 연결된다",
      "모국어는 중요하지 않다",
      "외국어 학습은 불필요하다",
    ],
    correctIndex: 1,
    explanation: "Language connects to identity and culture.",
    explanationVi: "Ngôn ngữ gắn với bản sắc và văn hóa.",
  },

  // IBT writing awareness
  {
    id: "ibt-w-01",
    level: 3,
    type: "multiple_choice",
    category: "writing",
    examSection: "writing",
    question: "IBT 쓰기 시험에서 타이핑 속도 목표는?",
    questionVi: "Mục tiêu tốc độ gõ IBT?",
    options: ["10자/분", "30–40자/분", "100자/분", "속도 무관"],
    correctIndex: 1,
    explanation: "IBT requires 30-40 Korean characters per minute.",
    explanationVi: "IBT cần 30–40 ký tự/phút.",
  },
  {
    id: "ibt-l-01",
    level: 2,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "다음을 듣고 맞는 응답은? (지하철 안내)",
    questionVi: "Nghe thông báo tàu điện ngầm — đáp án đúng?",
    options: [
      "다음 역은 시청입니다",
      "열차가 출발합니다",
      "표를 사세요",
      "문이 닫힙니다",
    ],
    correctIndex: 0,
    explanation: "Next station is City Hall.",
    explanationVi: "Ga tiếp theo là tòa thị chính.",
    listeningScript: "다음 역은 시청입니다. 내리실 문은 왼쪽입니다.",
    listeningScriptVi: "Ga tiếp theo là Tòa thị chính. Cửa xuống bên trái.",
  },
];
