import type { TopikQuizQuestion } from "@/topik/types";

/** IBT-style sentence ordering — original content, not past papers */
export const TOPIK_IBT_ORDER_BANK: TopikQuizQuestion[] = [
  {
    id: "ibt-ord-l2-01",
    level: 2,
    type: "sentence_order",
    category: "reading",
    examSection: "reading",
    question: "다음 문장을 올바른 순서로 배열하세요.",
    questionVi: "Sắp xếp các câu theo thứ tự đúng.",
    fragments: ["저는 학생입니다.", "한국어를 배웁니다.", "매일 학교에 갑니다."],
    correctOrder: [0, 2, 1],
    explanation: "Introduce self → daily routine → what you study.",
    explanationVi: "Giới thiệu bản thân → đi học hàng ngày → học tiếng Hàn.",
  },
  {
    id: "ibt-ord-l2-02",
    level: 2,
    type: "sentence_order",
    category: "reading",
    examSection: "reading",
    question: "다음 문장을 올바른 순서로 배열하세요.",
    questionVi: "Sắp xếp các câu theo thứ tự đúng.",
    fragments: ["오늘 날씨가 좋습니다.", "공원에 갔습니다.", "친구와 사진을 찍었습니다."],
    correctOrder: [0, 1, 2],
    explanation: "Weather → go to park → take photos.",
    explanationVi: "Thời tiết → đi công viên → chụp ảnh.",
  },
  {
    id: "ibt-ord-l3-01",
    level: 3,
    type: "sentence_order",
    category: "reading",
    examSection: "reading",
    question: "다음 문장을 올바른 순서로 배열하세요.",
    questionVi: "Sắp xếp các câu theo thứ tự đúng.",
    fragments: [
      "한국에 온 지 6개월이 됐습니다.",
      "처음에는 한국어가 어려웠습니다.",
      "지금은 간단한 대화를 할 수 있습니다.",
    ],
    correctOrder: [0, 1, 2],
    explanation: "Time in Korea → difficulty → current ability.",
    explanationVi: "Thời gian ở Hàn → khó khăn → khả năng hiện tại.",
  },
  {
    id: "ibt-ord-l3-02",
    level: 3,
    type: "sentence_order",
    category: "reading",
    examSection: "reading",
    question: "다음 문장을 올바른 순서로 배열하세요.",
    questionVi: "Sắp xếp các câu theo thứ tự đúng.",
    fragments: [
      "TOPIK 시험을 준비하고 있습니다.",
      "매일 30분씩 듣기 연습을 합니다.",
      "틀린 문제는 오답 노트에 적습니다.",
    ],
    correctOrder: [0, 1, 2],
    explanation: "Goal → daily practice → wrong notes habit.",
    explanationVi: "Mục tiêu thi → luyện nghe → ghi sai sót.",
  },
  {
    id: "ibt-ord-l3-03",
    level: 3,
    type: "sentence_order",
    category: "reading",
    examSection: "reading",
    question: "다음 문장을 올바른 순서로 배열하세요.",
    questionVi: "Sắp xếp các câu theo thứ tự đúng.",
    fragments: [
      "베트남에서 한국으로 유학을 왔습니다.",
      "처음에는 음식이 매웠습니다.",
      "이제는 김치도 잘 먹습니다.",
    ],
    correctOrder: [0, 1, 2],
    explanation: "Study abroad → spicy food → adapted to kimchi.",
    explanationVi: "Du học → đồ ăn cay → quen kimchi.",
  },
  {
    id: "ibt-ord-l4-01",
    level: 4,
    type: "sentence_order",
    category: "reading",
    examSection: "reading",
    question: "다음 문장을 올바른 순서로 배열하세요.",
    questionVi: "Sắp xếp các câu theo thứ tự đúng.",
    fragments: [
      "환경 문제는 전 세계적인 관심사입니다.",
      "플라스틱 사용을 줄이는 것이 중요합니다.",
      "개인도 작은 실천부터 시작할 수 있습니다.",
    ],
    correctOrder: [0, 1, 2],
    explanation: "Global issue → reduce plastic → individual action.",
    explanationVi: "Vấn đề toàn cầu → giảm nhựa → hành động cá nhân.",
  },
  {
    id: "ibt-ord-l4-02",
    level: 4,
    type: "sentence_order",
    category: "reading",
    examSection: "reading",
    question: "다음 문장을 올바른 순서로 배열하세요.",
    questionVi: "Sắp xếp các câu theo thứ tự đúng.",
    fragments: [
      "IBT 시험은 컴퓨터로 진행됩니다.",
      "따라서 타이핑 속도도 중요합니다.",
      "매일 30분씩 연습하는 것을 추천합니다.",
    ],
    correctOrder: [0, 1, 2],
    explanation: "IBT format → typing matters → daily practice tip.",
    explanationVi: "Thi IBT → tốc độ gõ → luyện mỗi ngày.",
  },
  {
    id: "ibt-ord-l4-03",
    level: 4,
    type: "sentence_order",
    category: "reading",
    examSection: "reading",
    question: "다음 문장을 올바른 순서로 배열하세요.",
    questionVi: "Sắp xếp các câu theo thứ tự đúng.",
    fragments: [
      "듣기 문제를 풀 때는 집중이 필요합니다.",
      "한 번만 듣고 바로 답을 고르지 마세요.",
      "메모를 하면서 핵심을 찾는 연습을 하세요.",
    ],
    correctOrder: [0, 1, 2],
    explanation: "Focus needed → don't rush → note-taking tip.",
    explanationVi: "Cần tập trung → đừng vội → ghi chú.",
  },
];
