import type { TopikQuizQuestion } from "@/topik/types";

/** Extra drill-focused listening & reading — original content */
export const TOPIK_DRILL_BANK: TopikQuizQuestion[] = [
  // Listening L1-L2
  {
    id: "drill-l1-l01",
    level: 1,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "남자는 어디에 갑니까?",
    questionVi: "Người đàn ông đi đâu?",
    options: ["학교", "병원", "회사", "시장"],
    correctIndex: 0,
    explanation: "He goes to school.",
    explanationVi: "Anh ấy đi học.",
    listeningScript: "아침에 학교에 가요.",
    listeningScriptVi: "Buổi sáng tôi đi học.",
  },
  {
    id: "drill-l1-l02",
    level: 1,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "오늘은 무슨 요일입니까?",
    questionVi: "Hôm nay là thứ mấy?",
    options: ["월요일", "화요일", "수요일", "목요일"],
    correctIndex: 2,
    explanation: "Today is Wednesday.",
    explanationVi: "Hôm nay là thứ Tư.",
    listeningScript: "오늘은 수요일이에요.",
    listeningScriptVi: "Hôm nay là thứ Tư.",
  },
  {
    id: "drill-l2-l01",
    level: 2,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "여자는 무엇을 사려고 합니까?",
    questionVi: "Người phụ nữ định mua gì?",
    options: ["우유", "빵", "과일", "책"],
    correctIndex: 0,
    explanation: "She wants to buy milk.",
    explanationVi: "Cô ấy muốn mua sữa.",
    listeningScript: "슈퍼마켓에서 우유를 사려고 해요.",
    listeningScriptVi: "Tôi định mua sữa ở siêu thị.",
  },
  {
    id: "drill-l2-l02",
    level: 2,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "버스를 타고 어디에 갑니까?",
    questionVi: "Đi xe buýt đến đâu?",
    options: ["공항", "역", "공원", "도서관"],
    correctIndex: 1,
    explanation: "They take the bus to the station.",
    explanationVi: "Họ đi xe buýt đến ga.",
    listeningScript: "버스를 타고 역에 가요.",
    listeningScriptVi: "Đi xe buýt đến ga.",
  },
  // Listening L3-L4
  {
    id: "drill-l3-l01",
    level: 3,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "남자의 직업은 무엇입니까?",
    questionVi: "Nghề nghiệp của người đàn ông là gì?",
    options: ["의사", "기자", "요리사", "변호사"],
    correctIndex: 1,
    explanation: "He is a journalist.",
    explanationVi: "Anh ấy là phóng viên.",
    listeningScript: "저는 신문사에서 일하는 기자입니다.",
    listeningScriptVi: "Tôi là phóng viên làm việc ở tòa soạn báo.",
  },
  {
    id: "drill-l3-l02",
    level: 3,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "회의는 몇 시에 시작합니까?",
    questionVi: "Cuộc họp bắt đầu lúc mấy giờ?",
    options: ["2시", "3시", "4시", "5시"],
    correctIndex: 2,
    explanation: "The meeting starts at 4.",
    explanationVi: "Cuộc họp bắt đầu lúc 4 giờ.",
    listeningScript: "오후 4시에 회의가 시작됩니다.",
    listeningScriptVi: "Cuộc họp bắt đầu lúc 4 giờ chiều.",
  },
  {
    id: "drill-l4-l01",
    level: 4,
    type: "multiple_choice",
    category: "listening",
    examSection: "listening",
    question: "화자가 제안하는 해결책은 무엇입니까?",
    questionVi: "Giải pháp người nói đề xuất là gì?",
    options: ["재활용 분리", "대중교통 이용", "에너지 절약", "온라인 수업"],
    correctIndex: 0,
    explanation: "Separate recycling.",
    explanationVi: "Phân loại tái chế.",
    listeningScript: "쓰레기를 분리해서 버리면 환경 보호에 도움이 됩니다.",
    listeningScriptVi: "Phân loại rác giúp bảo vệ môi trường.",
  },
  // Reading L2-L3
  {
    id: "drill-l2-r01",
    level: 2,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    question: "글의 주제는 무엇입니까?",
    questionVi: "Chủ đề của đoạn văn là gì?",
    passage: "민수는 매일 아침 6시에 일어납니다. 운동을 하고 아침을 먹은 후 버스를 타고 회사에 갑니다.",
    options: ["민수의 아침 일과", "회사 생활", "운동 방법", "버스 시간표"],
    correctIndex: 0,
    explanation: "The passage describes Min-su's morning routine.",
    explanationVi: "Đoạn văn mô tả thói quen buổi sáng của Min-su.",
  },
  {
    id: "drill-l3-r01",
    level: 3,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    question: "베트남 학생들이 한국어를 배우는 이유로 언급되지 않은 것은?",
    questionVi: "Lý do người Việt học tiếng Hàn KHÔNG được nhắc?",
    passage:
      "많은 베트남 학생들이 한국어를 배웁니다. 유학, 취업, K-pop 등 다양한 이유가 있습니다. TOPIK 점수는 유학과 취업에 중요합니다.",
    options: ["유학", "취업", "K-pop", "요리"],
    correctIndex: 3,
    explanation: "Cooking is not mentioned.",
    explanationVi: "Nấu ăn không được nhắc.",
  },
  {
    id: "drill-l3-r02",
    level: 3,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    question: "IBT 시험의 특징으로 맞는 것은?",
    questionVi: "Đặc điểm đúng của thi IBT?",
    passage: "TOPIK IBT는 컴퓨터로 치르는 시험입니다. 듣기, 읽기, 쓰기, 말하기 영역이 있습니다. 타이핑 속도도 중요합니다.",
    options: ["종이 시험", "컴퓨터 시험", "듣기만 있음", "말하기 없음"],
    correctIndex: 1,
    explanation: "IBT is a computer-based test.",
    explanationVi: "IBT là thi trên máy tính.",
  },
  {
    id: "drill-l4-r01",
    level: 4,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    question: "글쓴이의 의견으로 가장 적절한 것은?",
    questionVi: "Ý kiến phù hợp nhất của tác giả?",
    passage:
      "시험 준비에서 오답 노트는 매우 유용합니다. 틀린 문제를 반복해서 풀면 같은 실수를 줄일 수 있습니다. 새 문제만 푸는 것보다 효과적입니다.",
    options: [
      "오답 노트는 시간 낭비다",
      "오답 반복 학습이 효과적이다",
      "새 문제만 풀어야 한다",
      "시험 준비는 불필요하다",
    ],
    correctIndex: 1,
    explanation: "Wrong-note review is effective.",
    explanationVi: "Ôn lại câu sai rất hiệu quả.",
  },
  {
    id: "drill-l4-r02",
    level: 4,
    type: "multiple_choice",
    category: "reading",
    examSection: "reading",
    question: "듣기 연습 시 권장되는 방법은?",
    questionVi: "Phương pháp luyện nghe được khuyên?",
    passage:
      "듣기 실력을 키우려면 스크립트를 활용하는 것이 좋습니다. 먼저 듣고, 모르는 부분은 스크립트로 확인한 후 다시 듣습니다. 매일 조금씩 연습하세요.",
    options: ["한 번만 듣기", "스크립트 활용 후 반복", "소리 끄고 읽기", "시험 전날만 연습"],
    correctIndex: 1,
    explanation: "Use script then replay.",
    explanationVi: "Dùng script rồi nghe lại.",
  },
];
