import { defaultPickupWindow } from "./format";
import type { GiuAccount, GiuBox, GiuMerchant } from "./types";

const { start, end, expires } = defaultPickupWindow();

/** Demo login: minseong@giucuu.com / minseong1234 (customer & merchant roles) */
export const SEED_DEMO_PASSWORD = "minseong1234";

export const SEED_DEMO_CUSTOMER: GiuAccount = {
  id: "acc_minseong_customer",
  role: "customer",
  email: "minseong@giucuu.com",
  phone: "01012345678",
  passwordHash: "$2b$12$raI/PFY2vPd2VEdgvfrgDuWHnzzB54c0JfLRlKOPehODxiBlUCvQy",
  name: "민성",
  market: "kr",
  createdAt: "2026-01-01T00:00:00.000Z",
};

export const SEED_DEMO_MERCHANT_ACCOUNT: GiuAccount = {
  id: "acc_minseong_merchant",
  role: "merchant",
  email: "minseong@giucuu.com",
  phone: "01087654321",
  passwordHash: "$2b$12$raI/PFY2vPd2VEdgvfrgDuWHnzzB54c0JfLRlKOPehODxiBlUCvQy",
  name: "민성",
  market: "kr",
  merchantId: "mer_minseong_demo",
  createdAt: "2026-01-01T00:00:00.000Z",
};

export const SEED_DEMO_MERCHANT: GiuMerchant = {
  id: "mer_minseong_demo",
  accountId: "acc_minseong_merchant",
  name: "민성 마감베이커리",
  slug: "minseong-bakery",
  category: "bakery",
  district: "icn_yeonsu",
  address: "인천 연수구 센트럴로 1",
  phone: "01087654321",
  verified: true,
  rating: 5,
  reviewCount: 1,
  rescuedBoxes: 0,
  market: "kr",
  createdAt: "2026-01-01T00:00:00.000Z",
};

const SEED_MERCHANTS_RAW: Omit<GiuMerchant, "accountId" | "market">[] = [
  {
    id: "mer_seed_001",
    name: "송도 크러스트 베이커리",
    slug: "songdo-crust-bakery",
    category: "bakery",
    district: "icn_yeonsu",
    address: "인천 연수구 컨벤시아대로 123",
    addressHint: "송도 센트럴파크 인근",
    phone: "0321234001",
    verified: true,
    rating: 4.9,
    reviewCount: 128,
    rescuedBoxes: 420,
    createdAt: "2025-09-01T08:00:00.000Z",
  },
  {
    id: "mer_seed_002",
    name: "구월 오후카페",
    slug: "guwol-afternoon-cafe",
    category: "cafe",
    district: "icn_namdong",
    address: "인천 남동구 인하로 45",
    phone: "0321234002",
    verified: true,
    rating: 4.8,
    reviewCount: 86,
    rescuedBoxes: 210,
    createdAt: "2025-10-15T08:00:00.000Z",
  },
  {
    id: "mer_seed_003",
    name: "부평 하루빵",
    slug: "bupyeong-haru-bbang",
    category: "bakery",
    district: "icn_bupyeong",
    address: "인천 부평구 부평대로 88",
    phone: "0321234003",
    verified: true,
    rating: 4.7,
    reviewCount: 64,
    rescuedBoxes: 310,
    createdAt: "2025-08-20T08:00:00.000Z",
  },
  {
    id: "mer_seed_004",
    name: "주안 스윗코너",
    slug: "juan-sweet-corner",
    category: "cafe",
    district: "icn_michuhol",
    address: "인천 미추홀구 주안로 12",
    phone: "0321234004",
    verified: true,
    rating: 4.6,
    reviewCount: 41,
    rescuedBoxes: 150,
    createdAt: "2025-11-01T08:00:00.000Z",
  },
  {
    id: "mer_seed_005",
    name: "청라 밀크브레드",
    slug: "cheongna-milk-bread",
    category: "bakery",
    district: "icn_seo",
    address: "인천 서구 청라대로 200",
    phone: "0321234005",
    verified: true,
    rating: 4.8,
    reviewCount: 55,
    rescuedBoxes: 190,
    createdAt: "2025-07-12T08:00:00.000Z",
  },
  {
    id: "mer_seed_006",
    name: "동인천 옛골목빵집",
    slug: "dongincheon-bakery",
    category: "bakery",
    district: "icn_jung",
    address: "인천 중구 차이나타운로 7",
    phone: "0321234006",
    verified: true,
    rating: 4.5,
    reviewCount: 38,
    rescuedBoxes: 240,
    createdAt: "2025-06-01T08:00:00.000Z",
  },
];

export const SEED_MERCHANTS: GiuMerchant[] = SEED_MERCHANTS_RAW.map((m) => ({
  ...m,
  accountId: `acc_${m.id}`,
  market: "kr" as const,
}));

export const SEED_BOXES: GiuBox[] = [
  {
    id: "box_seed_001",
    merchantId: "mer_seed_001",
    title: "마감 럭키백 · 식빵·페이스트리",
    description: "식빵·크로와상·쿠키 중 랜덤 3~4개",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
    category: "bakery",
    originalPriceVnd: 12_000,
    salePriceVnd: 6_000,
    quantityTotal: 8,
    quantityLeft: 5,
    pickupStart: start,
    pickupEnd: end,
    freshnessNote: "픽업 전까지 매장에서 보관합니다.",
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_002",
    merchantId: "mer_seed_002",
    title: "마감 디저트 세트",
    description: "케이크·쿠키·음료 중 랜덤",
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    category: "cafe",
    originalPriceVnd: 14_000,
    salePriceVnd: 7_000,
    quantityTotal: 5,
    quantityLeft: 3,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_003",
    merchantId: "mer_seed_003",
    title: "오늘 빵 마감백",
    description: "단팥빵·소보로·식빵 믹스",
    imageUrl: "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800&q=80",
    category: "bakery",
    originalPriceVnd: 10_000,
    salePriceVnd: 5_000,
    quantityTotal: 10,
    quantityLeft: 7,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_004",
    merchantId: "mer_seed_004",
    title: "스윗 마감 럭키백",
    description: "디저트 2~3종",
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
    category: "cafe",
    originalPriceVnd: 12_000,
    salePriceVnd: 6_000,
    quantityTotal: 6,
    quantityLeft: 4,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_005",
    merchantId: "mer_seed_005",
    title: "밀크브레드 마감",
    description: "식빵·롤빵 랜덤",
    imageUrl: "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=800&q=80",
    category: "bakery",
    originalPriceVnd: 11_000,
    salePriceVnd: 5_500,
    quantityTotal: 4,
    quantityLeft: 2,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_006",
    merchantId: "mer_seed_006",
    title: "골목빵집 마감백",
    description: "당일 남은 빵 모음",
    imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&q=80",
    category: "bakery",
    originalPriceVnd: 9_000,
    salePriceVnd: 4_500,
    quantityTotal: 5,
    quantityLeft: 3,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
];

export const SEED_RESCUED_COUNT = 1280;
export const SEED_CO2_KG = 1536;
export const SEED_SAVED_VND = 7_680_000;
