import { defaultPickupWindow } from "./format";
import type { GiuBox, GiuMerchant } from "./types";

const { start, end, expires } = defaultPickupWindow();

const SEED_MERCHANTS_RAW: Omit<GiuMerchant, "accountId" | "market">[] = [
  {
    id: "mer_seed_001",
    name: "Bánh Mì Huynh Hoa",
    slug: "banh-mi-huynh-hoa",
    category: "banh_mi",
    district: "quan_1",
    address: "26 Lê Thị Riêng, Quận 1",
    addressHint: "Góc Pasteur",
    phone: "+84901234501",
    zalo: "+84901234501",
    verified: true,
    rating: 4.9,
    reviewCount: 312,
    rescuedBoxes: 890,
    createdAt: "2025-09-01T08:00:00.000Z",
  },
  {
    id: "mer_seed_002",
    name: "The Workshop Coffee",
    slug: "the-workshop-coffee",
    category: "cafe",
    district: "quan_1",
    address: "27 Ngô Đức Kế, Quận 1",
    phone: "+84901234502",
    zalo: "+84901234502",
    verified: true,
    rating: 4.8,
    reviewCount: 156,
    rescuedBoxes: 420,
    createdAt: "2025-10-15T08:00:00.000Z",
  },
  {
    id: "mer_seed_003",
    name: "Tous Les Jours Pasteur",
    slug: "tlj-pasteur",
    category: "bakery",
    district: "quan_3",
    address: "183 Pasteur, Quận 3",
    phone: "+84901234503",
    verified: true,
    rating: 4.7,
    reviewCount: 98,
    rescuedBoxes: 650,
    createdAt: "2025-08-20T08:00:00.000Z",
  },
  {
    id: "mer_seed_004",
    name: "Phúc Long Nguyễn Thị Minh Khai",
    slug: "phuc-long-ntmk",
    category: "tra_sua",
    district: "quan_3",
    address: "188 Nguyễn Thị Minh Khai, Quận 3",
    phone: "+84901234504",
    zalo: "+84901234504",
    verified: true,
    rating: 4.6,
    reviewCount: 74,
    rescuedBoxes: 280,
    createdAt: "2025-11-01T08:00:00.000Z",
  },
  {
    id: "mer_seed_005",
    name: "Pizza 4P's Saigon Pearl",
    slug: "pizza-4ps-saigon-pearl",
    category: "nha_hang",
    district: "quan_7",
    address: "Saigon Pearl, Quận 7",
    phone: "+84901234505",
    verified: true,
    rating: 4.9,
    reviewCount: 201,
    rescuedBoxes: 340,
    createdAt: "2025-07-10T08:00:00.000Z",
  },
  {
    id: "mer_seed_006",
    name: "Circle K Lê Văn Sỹ",
    slug: "circle-k-le-van-sy",
    category: "tap_hoa",
    district: "quan_3",
    address: "45 Lê Văn Sỹ, Quận 3",
    phone: "+84901234506",
    verified: true,
    rating: 4.5,
    reviewCount: 45,
    rescuedBoxes: 520,
    createdAt: "2025-12-01T08:00:00.000Z",
  },
  {
    id: "mer_seed_007",
    name: "Landmark Bakery",
    slug: "landmark-bakery",
    category: "bakery",
    district: "quan_7",
    address: "Vinhomes Central Park, Quận 7",
    phone: "+84901234507",
    verified: false,
    rating: 4.4,
    reviewCount: 22,
    rescuedBoxes: 95,
    createdAt: "2026-01-20T08:00:00.000Z",
  },
  {
    id: "mer_seed_008",
    name: "Highlands Coffee Bùi Viện",
    slug: "highlands-bui-vien",
    category: "cafe",
    district: "quan_1",
    address: "Bùi Viện, Quận 1",
    phone: "+84901234508",
    zalo: "+84901234508",
    verified: true,
    rating: 4.3,
    reviewCount: 88,
    rescuedBoxes: 410,
    createdAt: "2025-06-05T08:00:00.000Z",
  },
  {
    id: "mer_seed_009",
    name: "Saigon Hoa Tươi",
    slug: "saigon-hoa-tuoi",
    category: "hoa",
    district: "quan_10",
    address: "Chợ hoa Lê Văn Thọ, Quận 10",
    phone: "+84901234509",
    verified: true,
    rating: 4.8,
    reviewCount: 36,
    rescuedBoxes: 120,
    createdAt: "2026-02-01T08:00:00.000Z",
  },
  {
    id: "mer_seed_010",
    name: "Bánh Mì 37 Nguyễn Trãi",
    slug: "banh-mi-37-nguyen-trai",
    category: "banh_mi",
    district: "quan_5",
    address: "37 Nguyễn Trãi, Quận 5",
    phone: "+84901234510",
    verified: true,
    rating: 4.7,
    reviewCount: 167,
    rescuedBoxes: 780,
    createdAt: "2025-05-12T08:00:00.000Z",
  },
  {
    id: "mer_seed_011",
    name: "Starbucks Crescent Mall",
    slug: "starbucks-crescent",
    category: "cafe",
    district: "quan_7",
    address: "Crescent Mall, Quận 7",
    phone: "+84901234511",
    verified: true,
    rating: 4.5,
    reviewCount: 54,
    rescuedBoxes: 190,
    createdAt: "2025-11-18T08:00:00.000Z",
  },
  {
    id: "mer_seed_012",
    name: "FamilyMart Xô Viết Nghệ Tĩnh",
    slug: "familymart-xvnt",
    category: "tap_hoa",
    district: "binh_thanh",
    address: "Xô Viết Nghệ Tĩnh, Bình Thạnh",
    phone: "+84901234512",
    verified: true,
    rating: 4.4,
    reviewCount: 31,
    rescuedBoxes: 440,
    createdAt: "2025-09-22T08:00:00.000Z",
  },
];

export const SEED_MERCHANTS: GiuMerchant[] = SEED_MERCHANTS_RAW.map((m) => ({
  ...m,
  accountId: `acc_${m.id}`,
  market: "vn" as const,
}));

export const SEED_BOXES: GiuBox[] = [
  {
    id: "box_seed_001",
    merchantId: "mer_seed_001",
    title: "마감 반미 믹스 박스",
    description: "반미 3~4개, 아직 따뜻함",
    category: "banh_mi",
    originalPriceVnd: 120000,
    salePriceVnd: 45000,
    quantityTotal: 8,
    quantityLeft: 5,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_002",
    merchantId: "mer_seed_002",
    title: "디저트 + 커피 서프라이즈 백",
    description: "크루아상, 머핀, 커피 쿠폰",
    category: "cafe",
    originalPriceVnd: 180000,
    salePriceVnd: 65000,
    quantityTotal: 5,
    quantityLeft: 3,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_003",
    merchantId: "mer_seed_003",
    title: "단팥빵 & 케이크 서프라이즈",
    description: "베이커리 4~6개 믹스",
    category: "bakery",
    originalPriceVnd: 150000,
    salePriceVnd: 55000,
    quantityTotal: 10,
    quantityLeft: 7,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_004",
    merchantId: "mer_seed_004",
    title: "버블티 & 토핑 서프라이즈",
    description: "L사이즈 2잔 + 토핑",
    category: "tra_sua",
    originalPriceVnd: 110000,
    salePriceVnd: 40000,
    quantityTotal: 6,
    quantityLeft: 4,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_005",
    merchantId: "mer_seed_005",
    title: "피자 슬라이스 서프라이즈",
    description: "피자 3~4조각 믹스",
    category: "nha_hang",
    originalPriceVnd: 200000,
    salePriceVnd: 75000,
    quantityTotal: 4,
    quantityLeft: 2,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_006",
    merchantId: "mer_seed_006",
    title: "유통기한 임박 — 스낵 & 음료",
    description: "스낵·음료 5~8개 믹스",
    category: "tap_hoa",
    originalPriceVnd: 90000,
    salePriceVnd: 35000,
    quantityTotal: 12,
    quantityLeft: 9,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_007",
    merchantId: "mer_seed_007",
    title: "마감 신선 빵",
    category: "bakery",
    originalPriceVnd: 80000,
    salePriceVnd: 30000,
    quantityTotal: 5,
    quantityLeft: 5,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_008",
    merchantId: "mer_seed_008",
    title: "하이랜드 디저트",
    category: "cafe",
    originalPriceVnd: 100000,
    salePriceVnd: 38000,
    quantityTotal: 7,
    quantityLeft: 6,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_009",
    merchantId: "mer_seed_009",
    title: "마감 신선 꽃",
    description: "꽃다발 믹스, 아직 신선함",
    category: "hoa",
    originalPriceVnd: 250000,
    salePriceVnd: 85000,
    quantityTotal: 3,
    quantityLeft: 2,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_010",
    merchantId: "mer_seed_010",
    title: "햄 반미 믹스",
    category: "banh_mi",
    originalPriceVnd: 100000,
    salePriceVnd: 40000,
    quantityTotal: 10,
    quantityLeft: 8,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_011",
    merchantId: "mer_seed_011",
    title: "페이스트리 & 샌드위치 백",
    category: "cafe",
    originalPriceVnd: 160000,
    salePriceVnd: 60000,
    quantityTotal: 4,
    quantityLeft: 3,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
  {
    id: "box_seed_012",
    merchantId: "mer_seed_012",
    title: "오니기리 & 도시락 서프라이즈",
    category: "tap_hoa",
    originalPriceVnd: 70000,
    salePriceVnd: 28000,
    quantityTotal: 8,
    quantityLeft: 6,
    pickupStart: start,
    pickupEnd: end,
    status: "mo",
    createdAt: new Date().toISOString(),
    expiresAt: expires,
  },
];

export const SEED_RESCUED_COUNT = 2847;
export const SEED_CO2_KG = 7118;
export const SEED_SAVED_VND = 892_000_000;
