export const GIU_STRINGS = {
  brand: "Giu",
  tagline: "Giải cứu đồ ngon cuối ngày",
  city: "TP. Hồ Chí Minh",
  heroTitle: "Giải cứu đồ ngon sắp bị bỏ đi",
  heroSubtitle:
    "Bánh, cà phê, món ăn cuối ngày từ quán quanh bạn — giảm 50–70%, đặt là chạy qua lấy. Ngon nguyên vẹn, giá sinh viên.",
  ctaBrowse: "Săn hộp giải cứu",
  ctaMerchant: "Đăng quán miễn phí",
  goldenHour: "Giờ vàng 19h–21h — lúc quán dọn hàng cuối ngày",
  howItWorks: "Giải cứu trong 3 bước",
  step1Title: "Săn",
  step1Desc: "Tối mở Giu, xem các hộp giảm 50–70% quanh bạn.",
  step2Title: "Thanh toán an toàn",
  step2Desc:
    "Thanh toán qua Giu — tiền được giữ an toàn. Quán xác nhận bạn đã lấy hàng thì quán mới nhận tiền.",
  step3Title: "Lấy & khoe",
  step3Desc: "Tới quán trước giờ đóng, đọc mã, nhận hộp.",
  statsBoxes: "hộp đã giải cứu",
  statsCo2: "kg CO₂ giảm",
  statsSaved: "tiết kiệm",
  statsMerchants: "quán đối tác",
  emptyBoxes: "Chưa có hộp nào đang mở",
  emptyBoxesHint: "Để lại SĐT — tụi mình nhắn khi có hộp gần bạn.",
  trustTitle: "Vì sao chọn Giu?",
  trustSave: "Tiết kiệm 50–70%",
  trustSaveDesc: "Ăn ngon giá sinh viên, chất lượng như bình thường.",
  trustLocal: "Quán quanh bạn",
  trustLocalDesc: "Chỉ Quận 1, 3, 7, 10, Bình Thạnh, Phú Nhuận — mở rộng dần.",
  trustFree: "Đăng quán miễn phí",
  trustFreeDesc: "Quán chỉ trả phí khi có giao dịch thành công (12%).",
  trustEscrow: "Thanh toán an toàn Giu",
  trustEscrowDesc:
    "Tiền Giu giữ hộ — quán xác nhận lấy hàng xong mới chuyển. Giống 당근 안심결제.",
  escrowTitle: "Thanh toán an toàn Giu",
  escrowDesc:
    "Tiền được Giu giữ an toàn. Quán xác nhận bạn đã lấy hàng → tiền mới chuyển cho quán.",
  payCta: "Thanh toán an toàn & nhận mã",
  navHome: "Trang chủ",
  navBoxes: "Săn hộp",
  navMerchants: "Quán",
  navMy: "Mã của tôi",
  navPanel: "Quản lý quán",
  footer: "© Giu — Giải cứu đồ ngon TP.HCM",
  commissionNote: "Phí nền tảng 12% chỉ khi giao dịch thành công.",
  reserveCta: "Giải cứu ngay",
  merchantTitle: "Biến đồ thừa thành doanh thu",
  merchantSubtitle:
    "Đăng quán miễn phí. Cuối ngày đăng hộp bất ngờ — khách tới lấy, bạn gỡ vốn thay vì vứt.",
} as const;
