export const GIU_STRINGS = {
  brand: "GIU",
  tagline: "인천 마감 빵·디저트 반값",
  city: "인천",
  heroTitle: "마감 직전, 맛있는 빵을 반값에",
  heroSubtitle:
    "동네 베이커리·카페의 오늘 남은 빵과 디저트 — 약 50% 할인, 앱에서 예약하고 픽업하세요.",
  ctaBrowse: "근처 마감할인 보기",
  ctaMerchant: "가게 무료 입점",
  goldenHour: "마감할인",
  howItWorks: "3단계로 이용하기",
  step1Title: "찾기",
  step1Desc: "지도에서 근처 마감 박스를 확인하세요.",
  step2Title: "안전 결제",
  step2Desc:
    "앱에서 결제 — 금액은 안전하게 보관됩니다. 가게가 픽업을 확인하면 정산됩니다.",
  step3Title: "픽업",
  step3Desc: "픽업 시간에 매장 방문, 코드를 보여주고 받으세요.",
  statsBoxes: "구출한 박스",
  statsCo2: "kg CO₂ 절감",
  statsSaved: "절약 금액",
  statsMerchants: "제휴 가게",
  emptyBoxes: "현재 열린 박스가 없습니다",
  emptyBoxesHint: "알림을 남겨 주세요 — 박스가 생기면 알려드릴게요.",
  trustTitle: "왜 Giu인가요?",
  trustSave: "약 50% 절약",
  trustSaveDesc: "마감 직전 맛은 그대로, 합리적인 가격.",
  trustLocal: "인천 동네 가게",
  trustLocalDesc: "송도·구월·부평·주안부터 — 점점 확대 중.",
  trustFree: "가게 등록 무료",
  trustFreeDesc: "거래 성사 시에만 12% 수수료.",
  trustEscrow: "Giu 안전 결제",
  trustEscrowDesc: "결제 금액은 Giu가 안전하게 보관합니다.",
  escrowTitle: "Giu 안전 결제",
  escrowDesc: "결제 금액은 Giu가 안전하게 보관합니다.",
  payCta: "안전 결제 & 코드 받기",
  navHome: "홈",
  navBoxes: "지도",
  navFavorites: "즐겨찾기",
  navMerchants: "가게",
  navMy: "내 코드",
  navPanel: "가게 관리",
  footer: "© GIU — 인천 마감할인",
  commissionNote: "플랫폼 수수료 12% (거래 성사 시에만).",
  reserveCta: "예약하기",
  merchantTitle: "마감 재고를 매출로",
  merchantSubtitle:
    "입점비 0원. 마감 빵·디저트만 올리면 손님이 앱에서 결제하고 픽업합니다.",
} as const;
