export const GIU_STRINGS = {
  brand: "GIU",
  tagline: "호치민 맛있는 음식 구출",
  city: "호치민시",
  heroTitle: "버려질 뻔한 맛있는 음식을 구출하세요",
  heroSubtitle:
    "동네 가게의 빵, 커피, 마감 음식 — 50~70% 할인, 예약하고 바로 픽업. 신선하고 학생 가격.",
  ctaBrowse: "구출 박스 찾기",
  ctaMerchant: "가게 무료 등록",
  goldenHour: "언제든 구출",
  howItWorks: "3단계로 구출하기",
  step1Title: "찾기",
  step1Desc: "Giu를 열고 근처 할인 박스를 확인하세요.",
  step2Title: "안전 결제",
  step2Desc:
    "Giu로 결제 — 금액은 안전하게 보관됩니다. 가게가 픽업을 확인하면 가게에 정산됩니다.",
  step3Title: "픽업",
  step3Desc: "픽업 시간에 가게에 방문, 코드를 보여주고 박스를 받으세요.",
  statsBoxes: "구출한 박스",
  statsCo2: "kg CO₂ 절감",
  statsSaved: "절약 금액",
  statsMerchants: "제휴 가게",
  emptyBoxes: "현재 열린 박스가 없습니다",
  emptyBoxesHint: "전화번호를 남겨주세요 — 박스가 생기면 알려드릴게요.",
  trustTitle: "왜 Giu인가요?",
  trustSave: "50~70% 절약",
  trustSaveDesc: "맛은 그대로, 학생 가격으로 즐기세요.",
  trustLocal: "동네 가게",
  trustLocalDesc: "1·3·7·10군, 빈탄, 푸뉴안 — 점차 확대 중.",
  trustFree: "가게 등록 무료",
  trustFreeDesc: "거래 성사 시에만 12% 수수료.",
  trustEscrow: "Giu 안전 결제",
  trustEscrowDesc:
    "결제 금액은 Giu가 안전하게 보관합니다.",
  escrowTitle: "Giu 안전 결제",
  escrowDesc:
    "결제 금액은 Giu가 안전하게 보관합니다.",
  payCta: "안전 결제 & 코드 받기",
  navHome: "홈",
  navBoxes: "지도",
  navFavorites: "즐겨찾기",
  navMerchants: "가게",
  navMy: "내 코드",
  navPanel: "가게 관리",
  footer: "© GIU — 호치민 맛있는 음식 구출",
  commissionNote: "플랫폼 수수료 12% (거래 성사 시에만).",
  reserveCta: "지금 구출하기",
  merchantTitle: "남은 재고를 매출로",
  merchantSubtitle:
    "가게 등록 무료. 언제든 서프라이즈 박스 등록 — 손님이 픽업, 버리지 말고 회수하세요.",
} as const;
