/** Official Effiroad assets in /public (generated by scripts/process-effroad-logos.mjs) */
export const BRAND_LOGO_HORIZONTAL_SRC = "/logo-horizontal-light.png?v=6";
export const BRAND_LOGO_ICON_SRC = "/logo-icon-light.png?v=6";
/** Cream-backed lockups for beige surfaces */
export const BRAND_LOGO_HORIZONTAL_SOLID_SRC = "/logo-horizontal.png?v=6";
export const BRAND_LOGO_ICON_SOLID_SRC = "/logo-icon.png?v=6";
export const BRAND_MARK_SRC = "/logo-mark.png?v=6";
/** @deprecated Use BRAND_LOGO_ICON_SRC */
export const BRAND_LOGO_SRC = BRAND_LOGO_ICON_SRC;
/** @deprecated Wordmark is included in horizontal lockup */
export const BRAND_WORDMARK_SRC = BRAND_LOGO_HORIZONTAL_SRC;
