/** Auto-generated by scripts/process-effroad-logos.mjs — do not edit */
export const BRAND_HORIZONTAL_WIDTH = 720;
export const BRAND_HORIZONTAL_HEIGHT = 172;
export const BRAND_HORIZONTAL_RATIO = 720 / 172;
export const BRAND_SYMBOL_WIDTH = 512;
export const BRAND_SYMBOL_HEIGHT = 329;
