/** Official Effiroad assets in /public (generated by scripts/process-effroad-logos.mjs) */
export const BRAND_ASSET_VERSION = "13";

export const BRAND_LOGO_HORIZONTAL_SRC = "/logo-horizontal-light.png?v=13";
export const BRAND_LOGO_ICON_SRC = "/logo-icon-light.png?v=13";
export const BRAND_LOGO_HORIZONTAL_SOLID_SRC = "/logo-horizontal.png?v=13";
export const BRAND_LOGO_HORIZONTAL_FOOTER_SRC = "/logo-horizontal-footer.png?v=13";
export const BRAND_LOGO_ICON_SOLID_SRC = "/logo-icon.png?v=13";
export const BRAND_LOGO_ICON_HEADER_SRC = "/logo-icon-header.png?v=13";
export const BRAND_LOGO_ICON_SITE_SRC = "/logo-icon-site.png?v=13";
export const BRAND_MARK_SRC = "/logo-mark.png?v=13";
/** @deprecated Use BRAND_LOGO_ICON_SRC */
export const BRAND_LOGO_SRC = BRAND_LOGO_ICON_SRC;
/** @deprecated Wordmark is included in horizontal lockup */
export const BRAND_WORDMARK_SRC = BRAND_LOGO_HORIZONTAL_SRC;

export type BrandLogoSurface = "default" | "header" | "footer" | "dark";

export function pickBrandIconSrc(surface: BrandLogoSurface = "default") {
  if (surface === "footer") return BRAND_LOGO_ICON_SOLID_SRC;
  if (surface === "header") return BRAND_LOGO_ICON_HEADER_SRC;
  if (surface === "dark") return BRAND_LOGO_ICON_SRC;
  return BRAND_LOGO_ICON_SRC;
}

export function pickBrandHorizontalSrc(surface: BrandLogoSurface = "default") {
  if (surface === "footer") return BRAND_LOGO_HORIZONTAL_FOOTER_SRC;
  if (surface === "header") return BRAND_LOGO_HORIZONTAL_SOLID_SRC;
  return BRAND_LOGO_HORIZONTAL_SRC;
}
