import { SITE } from "./constants";
import { SETTINGS_PAGE_EN } from "./content-settings-en-backup";

export const settingsPageEn = {
  ...SETTINGS_PAGE_EN,
  title: "Shop settings",
  subtitle: "Smart auto-dispatch, crew texts, and optional follow-ups — then one-time go-live steps.",
  badge: "Go live",
  backDashboardLink: "← Dashboard",
  productSectionTitle: "Your trade & how jobs run",
  productSectionSubtitle:
    "Start with your trade (restoration or HVAC). Then set shop name, dispatch rules for that trade, and who gets crew texts. Tap Save (top right) when done.",
  goLiveSectionTitle: "Go live checklist",
  goLiveSectionSubtitle: "Follow the steps in order — then save once at the bottom.",
  progressHint: "Trade → Contact → Hours → Forwarding. Jobber is optional.",
  scrollHint: "Trade → Dispatch → Crew → Save",
  allDone:
    "You're live. Clear jobs for your trade can auto-dispatch — safety holds and unclear calls wait for your OK.",
  ownerAlertsDescription:
    "Texts to your cell: booked visits (FYI), P1 urgent alerts, unclear intakes (1 / 2), or 9 to undo. Email is backup.",
  bookingPolicyTitle: "Dispatch & booking",
  bookingSectionTitle: "When jobs go out",
  bookingSchedulingEnabledLabel: "Let customers pick a visit time",
  bookingSchedulingModeLabel: "What happens after they pick a time",
  ownerApprovalSmsLabel: "When to text me for approval",
  ownerApprovalSmsHint: "Only applies when a booking needs your OK before it goes on the calendar.",
  bookingSavedLabel: "Saved",
  bookingLoadingLabel: "Loading...",
  bookingTryAgainLabel: "Try again",
  bookingPolicyDescription:
    "Routine water jobs can go straight to crew. Fire, sewage, or unclear calls wait for your OK.",
  smartAutoBookingTitle: "Auto-dispatch rules",
  smartAutoBookingIntro: "You don't pick these case-by-case — Effiroad applies them on every call.",
  smartAutoBookingRules: [
    "Clear water loss → crew text goes out.",
    "Fire, Cat-3, or missing details → we text you first (reply 1 = go, 2 = pass).",
    "Auto-booked by mistake? Reply 9 within the undo window below.",
  ] as readonly string[],
  bookingAdvancedTitle: "Advanced (optional)",
  bookingAdvancedHint: "Storm weeks, ZIP limits, and practice mode. Most shops skip this at first.",
  visitTimingTitle: "Time between visits",
  visitTimingHint:
    "How far apart customer-facing start times appear — e.g. every 2 hours (drive time is folded in automatically).",
  visitHoursTitle: "Visit hours",
  visitHoursHint: "When customers can book (Mon–Sat). Separate from your AI answer hours in Step 2.",
  visitHoursLayoutLabel: "Schedule style",
  visitHoursLayoutSplit: "Morning & afternoon",
  visitHoursLayoutContinuous: "One continuous block",
  visitHoursAmLabel: "Morning block",
  visitHoursPmLabel: "Afternoon block",
  visitHoursContinuousStartLabel: "Doors open",
  visitHoursContinuousEndLabel: "Last slot ends by",
  visitHoursToLabel: "to",
  visitHoursExample: (am: string, pm: string) =>
    `Example slots on the next open day: ${am} and ${pm}.`,
  visitHoursExampleContinuous: (range: string) =>
    `Example slots on the next open day: ${range} (back-to-back).`,
  appointmentIntervalLabel: "Slot spacing (start times customers see)",
  appointmentIntervalHint:
    "We offer visits this far apart. Visit length + drive time are balanced so the same tech isn't double-booked.",
  appointmentIntervalExample: (hours: number, minutes: number) =>
    minutes > 0
      ? `Example: first visit at 8:00 AM → next at ${8 + hours}:${String(minutes).padStart(2, "0")} AM (${hours}h ${minutes}m apart).`
      : `Example: first visit at 8:00 AM → next at ${8 + hours}:00 AM (${hours}-hour spacing).`,
  appointmentIntervalPresets: ["1 hr", "1.5 hr", "2 hr", "3 hr"] as const,
  travelMinutesLabel: "Drive time",
  travelMinutesHint:
    "Time to drive and park between jobs. Changing drive time keeps your slot spacing — visit length adjusts automatically.",
  travelMinutesFieldLabel: "Travel time (minutes)",
  teamCapacityTitle: "Multiple crews (optional)",
  teamCapacityHint: "Leave at 1 unless several techs can run jobs at the same time.",
  maxConcurrentVisitsLabel: "Jobs at the same time",
  maxConcurrentVisitsHint:
    "How many visits your team can run in the same window. 3 crews: set 3.",
  undoWindowLabel: "Cancel auto-book window (minutes)",
  undoWindowHint:
    "After Effiroad auto-confirms a visit, we text you. Reply 9 within this time to undo and review it yourself.",
  shadowModeLabel: "Practice mode",
  shadowModeIntro: "Test calls without touching Jobber or sending real customer texts.",
  shadowModeLive: "0 = Live — real texts, calendar, and Jobber.",
  shadowModePractice: "1+ = Practice — slots held, SMS tagged [TEST], drops by 1 per test call.",
  testModeTitle: "Test mode",
  testModeIntro:
    "Practice calls like live. Customer SMS are tagged [TEST] and Jobber stays off until you switch to Live.",
  testModeOn: "Test mode ON — not live yet",
  testModeOff: "Live — real dispatches and customer texts",
  testModeLoading: "Loading test mode…",
  testModeSaveError: "Could not save test mode. Try again.",
  testModeForwardingHint:
    "Turn test mode ON, call your shop line from another phone, check the dashboard, then turn OFF when you are ready for live traffic.",
  stormModeLabel: "High-volume / storm mode",
  stormModeHint:
    "Turn on during storms or call spikes — shorter prompts and a “we’re busy” message. Turn off when things calm down.",
  stormModeToggleLabel: "Enable high-volume mode on incoming calls",
  onCallScheduleLabel: "On-call by day",
  onCallScheduleHint: "Who gets the first crew text each weekday. Default = round-robin.",
  onCallWeekdayLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] as const,
  onCallNoneOption: "Round-robin (default)",
  serviceAreaZipsLabel: "Service ZIPs",
  serviceAreaZipsHint: "Only these ZIPs auto-dispatch. Leave blank for anywhere.",
  techDispatchTitle: "Crew assignment",
  techDispatchNav: "Crew assign",
  saveAllButton: "Save",
  saveAllSaving: "Saving…",
  saveAllSuccess: "All settings saved.",
  saveAllHint: "Change anything above, then save once here.",
  saveAllError: "Could not save everything. Check the fields and try again.",
  goLiveWelcome: "Go live in ~10 minutes",
  goLiveWelcomeHint: "Steps 1→5. Fill each page, tap Next, then Save (top right) when done.",
  goLiveNavContact: "Contact",
  goLiveNavSchedule: "Hours",
  goLiveNavPhone: "Forwarding",
  goLiveNavJobber: "Jobber",
  goLiveNavShop: "Shop setup",
  wizardStepOf: "Step {current} of {total}",
  wizardBack: "← Back",
  wizardContinue: "Next →",
  wizardLastStepHint: "Use Save (top right) when you change anything.",
  wizardStepComplete: "This step is saved — you can continue or go back to edit.",
  wizardContactRequired: "Enter email and mobile above (required fields marked *).",
  wizardScheduleRequired: "Finish contact first, then pick at least one answer-hours block.",
  wizardPhonePickPath: "Pick your phone path first — quiz or full list.",
  wizardPhoneRequired: "Wait for your Effiroad number or tap Provision below.",
  contactRequiredMark: "Required",
  contactQuickTip: "New requests and approve/pass texts go to this phone. Reply 1 or 2 from the truck.",
  scheduleQuickTip: "Effiroad only answers during these windows. Keep daytime calls on your team.",
  phoneQuickTip: "Customers still dial your shop number — unanswered calls forward to Effiroad.",
  jobberQuickTip: "Connect → Jobber login → Allow Access. Optional if you don't use Jobber.",
  jobberScheduleAutoNote:
    "After you connect once, approved visits sync to Jobber automatically — nothing else to set up.",
  editLabel: "Edit",
  collapseLabel: "Done",
  jobberPanel: {
    tagline: "One connect. Approved visits sync to Jobber on their own.",
    statusConnected: "Connected",
    statusOptional: "Optional",
    connectTitle: "Connect Jobber",
    features: {
      requests: {
        title: "Auto-create Requests",
        body: "Approved job cards become Jobber Requests — no copy-paste.",
      },
      schedule: {
        title: "Calendar sync",
        body: "Confirmed visit times land on your Jobber calendar right away.",
      },
      optional: {
        title: "Optional",
        body: "You can review and approve by text without Jobber.",
      },
    },
  },
  bookingNav: "Booking",
  techDispatchSummary:
    "On confirm, Effiroad texts one tech at a time (round-robin). Reply 1=accept, 2=pass.",
  agreementNav: "PM plans",
  shopNameNav: "Shop name",
  shopName: {
    label: "Shop name",
    hint: "Shows in every call greeting and customer text — e.g. “Thanks for calling ABC Restoration.”",
    placeholder: "ABC Restoration",
    save: "Save shop name",
    saving: "Saving…",
    saved: "Saved — texts and calls will use this name.",
    loading: "Loading…",
    loadError: "Couldn't load shop name. Refresh and try again.",
    saveError: "Couldn't save. Try again.",
    required: "Enter your shop name.",
  },
  agreementKeeper: {
    title: "Maintenance plans (PM)",
    summary:
      "After a job is done, text your PM offer to customers who opted in at intake. Optional — skip if you don't sell plans yet.",
    enabledLabel: "Enable Agreement Keeper",
    offerAfterComplete:
      "SMS maintenance plan offer when a job is marked complete (marketing opt-in required)",
    defaultPlan: "Default plan name",
    defaultPrice: "Annual price (USD)",
    visitsPerYear: "Tune-ups per year",
    offerExpires: "Offer link expires (days)",
    reminderHint: "Owner reminders at 60/30/7 days; customer reminders at 30/7 before renewal.",
    loading: "Loading…",
    saving: "Saving…",
    save: "Save PM settings",
    saved: "Saved",
  },
  shopOptional: {
    title: "Optional extras",
    summary: "PM plans, Google reviews, SMS registration. Safe to skip for now.",
    expandLabel: "Show",
    smsTitle: "SMS registration (US)",
    smsBody:
      "Carriers require business SMS registration before high-volume texting. Effiroad sends through your Twilio number — register your shop once in Trust Hub.",
    smsLink: "https://console.twilio.com/us1/develop/sms/trust-hub",
    smsLinkLabel: "Open Twilio Trust Hub →",
  },
  googleReview: {
    title: "Google review link",
    hint: "Sent by SMS after job complete. Leave blank to skip.",
    placeholder: "https://g.page/r/...",
    invalidUrl: "Enter a valid https:// link.",
    saving: "Saving…",
    saved: "Saved",
  },
  smsCompliance: {
    title: "SMS compliance (A2P / 10DLC)",
    summary:
      "US carriers require business SMS registration before you text customers at scale. Effiroad sends through your Twilio number — you register the shop brand and campaign.",
    steps: [
      "In Twilio Console → Messaging → Trust Hub, register your business (EIN or sole prop).",
      "Create a Messaging Campaign for transactional alerts (booking updates, crew ETA).",
      "If you send promotional texts (reviews, PM plans, quote follow-ups), register a separate marketing campaign or include both use cases where Twilio allows.",
      "Link your Effiroad Twilio number to the approved campaign before going live.",
      "Collect SMS consent on intake — Effiroad records checkboxes; you must honor STOP replies (handled automatically).",
    ],
    twilioLink: "https://console.twilio.com/us1/develop/sms/trust-hub",
    twilioLinkLabel: "Open Twilio Trust Hub",
    note: "Terms place A2P/10DLC registration on the shop. Contact support if texts fail with carrier error 30007 or similar.",
  },
  serviceAreaZipsPlaceholder: "78701, 78702, 78745",
  sectionSteps: {
    shop: "1",
    contact: "2",
    schedule: "3",
    phone: "4",
    jobber: "5",
  } as const,
};

export const vowDashboardEn = {
  nav: {
    dashboard: "Dashboard",
    briefing: "Daily Briefing",
    ai: "Shop AI",
    requests: "Requests",
    calendar: "Calendar",
    missedCalls: "Leads captured",
    agreements: "PM plans",
    settings: "Settings",
    shopTools: "Shop tools",
    allMenus: "All menus",
  },
  calendar: {
    title: "Schedule calendar",
    subtitle: "Tap a date for that day's visits, then tap a booking for details.",
    refresh: "Refresh",
    loading: "Loading…",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    today: "Today",
    noEventsDay: "No bookings",
    selectDay: "Select a date to see visits here.",
    dayEventsTitle: (count: number) => `${count} booking${count === 1 ? "" : "s"}`,
    noEventsOnDay: "No bookings on this day.",
    backToDayList: "← Back to list",
    eventCount: (count: number) => `${count}`,
    sourceEffiroad: "Effiroad confirmed",
    sourceJobber: "Jobber",
    customer: "Customer",
    phone: "Phone",
    address: "Address",
    issue: "Issue",
    time: "Visit time",
    priority: "Priority",
    viewBooking: "View request",
    close: "Close",
    effiroadBookings: "Effiroad confirmed",
    jobberCalendar: "Jobber schedule",
    emptyNative: "No confirmed Effiroad visits yet.",
    emptyJobber: "No Jobber events or connection needed.",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] as const,
  },
  upgrade: {
    title: "Upgrade plan",
    body: "Unlimited after-hours AI answering and text approvals.",
    cta: "View plans",
    viewLanding: "View landing",
  },
  agreements: {
    eyebrow: "Agreement Keeper",
    title: "Catch the call. Keep the contract.",
    subtitle:
      "Turn completed jobs into maintenance plans. Track renewals, import your spreadsheet, and get SMS reminders before contracts lapse.",
    settingsLink: "PM settings",
    addButton: "Add agreement",
    kpiActive: "Active plans",
    kpiRenewing: "Renewing in 30 days",
    kpiMrr: "Est. monthly recurring",
    filters: { all: "All", active: "Active", renewing: "Renewing soon" },
    importCsv: "Import CSV",
    importing: "Importing…",
    loading: "Loading agreements…",
    emptyTitle: "No maintenance plans yet",
    emptyBody: "Mark a job complete to auto-offer a plan, import a CSV, or add one manually.",
    emptyCta: "Add agreement",
    statusActive: "Active",
    statusDraft: "Draft",
    statusCancelled: "Cancelled",
    statusExpired: "Expired",
    statusPaused: "Paused",
    colCustomer: "Customer",
    colPlan: "Plan",
    colRenewal: "Renewal",
    colStatus: "Status",
    colPrice: "Annual",
    daysLeft: (n: number) => `${n}d left`,
    addTitle: "New maintenance agreement",
    fieldName: "Customer name",
    fieldPhone: "Phone",
    fieldAddress: "Service address",
    fieldPlan: "Plan name",
    fieldStart: "Start date",
    fieldRenewal: "Renewal date",
    fieldPrice: "Annual price (USD)",
    fieldVisits: "Visits per year",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    saveError: "Could not save. Try again.",
    loadError: "Could not load agreements.",
    importDone: (n: number, skipped: number) =>
      `Imported ${n} agreement${n === 1 ? "" : "s"}${skipped ? ` (${skipped} skipped)` : ""}.`,
    importError: "Import failed. Check CSV columns.",
    close: "← Close",
    cancelAgreement: "Cancel plan",
    renewOneYear: "Renew +1 year",
  },
  briefingPage: {
    title: (shop: string) => `Today's briefing — ${shop}`,
    subtitle:
      "Quick look at requests, approvals, and urgent items. Summary looks at yesterday; metrics below are today so far.",
    aiSummary: "AI Summary",
    refreshing: "Refreshing…",
    urgentTitle: "Urgent requests",
    pendingTitle: "Pending requests",
    viewAll: "View all",
    review: "Review",
    retry: "Retry",
    noUrgent: "No urgent requests found.",
    noPending: "No pending requests.",
    noRequestedTime: "No requested time",
  },
  bookingsList: {
    back: "← Back to dashboard",
    title: "Requests",
    subtitle: "View all inbound requests and approval status.",
  },
  header: {
    newRequest: "New request",
    dateRange: (start: string, end: string) => `${start} – ${end}`,
    dateQuick: "Quick range",
    dateCustom: "Custom",
    dateFrom: "From",
    dateTo: "To",
    dateApply: "Apply",
    dateInvalid: "Start date must be before end date.",
    subtitle: "Auto-booked jobs land on the calendar. Pending review shows first.",
    simulateWorking: "AI processing… (10–20 sec)",
    simulateDone: "Test request created. Refreshing list.",
    simulateFail: "Could not create request. Check login and dev server.",
  },
  hero: {
    period: "This month",
    tagline: "After-hours calls that become calendar slots — not voicemail.",
    callsSaved: "Leads captured",
    aiAnswered: "AI answered calls",
    emergency: "Emergency requests",
    deltaFlat: "Same as last month",
    delta: (pct: number) => `vs last month ${pct > 0 ? "↑" : "↓"} ${Math.abs(pct)}%`,
  },
  secondary: {
    hint: "At a glance",
    body: "Numbers are from real call logs. New requests appear in the list below.",
  },
  kpi: {
    missedPrevented: "Leads captured",
    emergency: "Emergency",
    conversion: "Booking conversion",
    aiAnswered: "AI answered",
    vsPrior: (pct: number, period: string) =>
      pct === 0 ? `${period} · same as last month` : `${period} · last month ${pct > 0 ? "↑" : "↓"} ${Math.abs(pct)}%`,
  },
  compareLabel: "This month",
  trend: {
    title: "Trends",
    last30: "Last 30 days · daily",
    viewDetail: "View details",
  },
  insights: {
    title: "Call insights",
    thisMonth: "This month",
    delta: (pct: number) => (pct === 0 ? "—" : `${pct > 0 ? "↑" : "↓"} ${Math.abs(pct)}%`),
  },
  recentRequests: {
    title: "Recent requests",
    subtitle: "New customer inquiries — check first",
    viewAll: "View all",
    columns: {
      customer: "Customer",
      type: "Type",
      priority: "Priority",
      received: "Received",
      status: "Status",
    },
    empty: "No requests yet.",
  },
  upcoming: {
    title: "Upcoming · approved",
    empty: "No approved or scheduled visits yet.",
    confirmed: "Confirmed",
    pending: "In review",
  },
  tools: {
    title: "Tools",
    subtitle: "Job Card, call logs, integrations",
  },
};

export const dashboardPageEn = {
  title: "Dashboard",
  subtitle: "After-hours and overflow calls in one place. Emergencies surface by text first.",
  setupIncomplete: "Setup isn't finished. Complete integrations to start answering calls.",
  setupComplete: "Live — Effiroad is monitoring your line during configured windows. All call data stays in your account.",
  stats: {
    tonightCalls: "Tonight's calls",
    bookings: "Service requests",
    pendingApproval: "Pending approval",
  },
  scheduleTitle: "AI answer hours",
  scheduleEmpty: "No hours configured.",
  backOnboarding: "Finish setup",
};

export const authPagesEn = {
  form: {
    passwordConfirmLabel: "Confirm password",
    passwordMismatch: "Passwords don't match.",
    loading: "Working…",
    errorGeneric: "Request failed.",
    errorNetwork: "Network error. Try again.",
    backHome: "← Home",
  },
  login: {
    title: "Log in",
    subtitle: "Access your Effiroad dashboard.",
    methodLegend: "Sign in with",
    methodEmail: "Email",
    methodPhone: "Phone",
    emailLabel: "Email",
    phoneLabel: "Mobile number",
    phonePlaceholder: "(512) 555-0100",
    passwordLabel: "Password",
    submit: "Log in",
    noAccount: "No account?",
    signupLink: "Sign up",
    forgotLink: "Forgot password?",
    rememberMeLabel: "Keep me signed in on this device",
  },
  forgotPassword: {
    title: "Reset password",
    subtitleRequest: "We'll send a code to your email to set a new password.",
    subtitleRequestSms: "We'll text a code to your registered mobile number.",
    subtitleVerify: "Enter the 6-digit code from email or SMS.",
    subtitleReset: "Choose a new password.",
    subtitleDone: "Password updated.",
    emailLabel: "Email",
    phoneLabel: "Mobile number",
    phonePlaceholder: "(512) 555-0100",
    channelLabel: "Send code via",
    channelEmail: "Email",
    channelSms: "SMS",
    channelHint: "SMS goes only to your signup mobile number.",
    devEmailHint: "In local dev, check the terminal if email isn't configured.",
    sendCode: "Send code",
    codeLabel: "6-digit code",
    codeHint: "Enter within 10 minutes. Don't share this code.",
    verifyCode: "Verify",
    resendSms: "Resend SMS",
    resendSmsSuccess: "Code sent to your registered phone.",
    backToEmail: "← Re-enter email",
    newPasswordLabel: "New password",
    confirmPasswordLabel: "Confirm new password",
    resetPassword: "Update password",
    goLogin: "Log in",
    backLogin: "Back to login",
    sentMessage: "If an account exists, we sent a code.",
    sentMessageEmail: "If an account exists, we sent a code to your email.",
    sentMessageSms: "If an account exists, we texted a code to your phone.",
    doneMessage: "Password changed. Log in with your new password.",
    loading: "Working…",
    errorGeneric: "Request failed.",
    errorNetwork: "Network error. Try again.",
  },
  signup: {
    title: "Sign up",
    step1Label: "1. Your details",
    step2Label: "2. Verify",
    subtitle: "Enter your info, then tap Send code to verify. Your data is protected and never shared — 30-day money-back guarantee.",
    subtitleVerify: "After verifying, tap Create account to finish.",
    shopLabel: "Shop name",
    shopPlaceholder: "e.g. ABC Restoration",
    emailLabel: "Email",
    passwordLabel: "Password",
    passwordHint:
      "8+ characters with upper & lower case, a number, and a special character (!@#…)",
    phoneLabel: "Mobile number",
    phoneLabelRequired: "Mobile number (required)",
    phonePlaceholder: "(512) 555-0100",
    phoneHintRequired:
      "US mobile (+1) — used for new request texts and reply 1/2 approvals.",
    phoneHintSms: "We'll text your verification code here.",
    phoneRequired: "Enter your mobile number.",
    phoneRequiredSms: "Enter your mobile number for SMS verification.",
    verifyChannelLabel: "Send code via",
    verifyChannelEmail: "Email (recommended)",
    verifyChannelSms: "SMS",
    verifyChannelHint: "Code by email or SMS. Mobile is required above.",
    sendCode: "Send code",
    sendCodeNote: "Enter the 6-digit code, then tap Verify.",
    sendCodeCooldown: "Resend ({seconds}s)",
    sentCodeMessage: "Code sent. Check email or SMS.",
    codeLabel: "6-digit code",
    codeHint: "Enter within 10 minutes.",
    verifyCode: "Verify",
    verifiedMessage: "Verified. Tap Create account to finish.",
    completeSignup: "Create account",
    backToDetails: "← Edit details",
    hasAccount: "Already have an account?",
    loginLink: "Log in",
    consentTermsLabel:
      "I agree to the Terms of Service and Privacy Policy (required).",
    consentSmsLabel:
      "I agree to receive service-related text messages at my mobile number — verification codes, new job alerts, and reply 1/2 approvals. Msg & data rates may apply. Reply STOP to opt out. (required)",
    consentMarketingEmailLabel:
      "Optional — send me Effiroad product tips and updates by email.",
    consentMarketingSmsLabel:
      "Optional — send me Effiroad product tips and updates by text. Msg & data rates may apply. Reply STOP to opt out.",
    consentRequired: "Check all three required agreement boxes to continue.",
    consentLegalLegend: "Legal agreements",
    consentTermsLink: "Terms",
    consentPrivacyLink: "Privacy",
  },
};

export const legalPagesEn = {
  privacy: {
    title: "Privacy Policy",
    updated: "July 2026",
    sections: [
      {
        heading: "Information we collect",
        body: "Email, shop name, payment info (Lemon Squeezy), Jobber metadata when connected, and call logs when intake is enabled.",
      },
      {
        heading: "How we use it",
        body: "To provide the service, billing, after-hours call handling, Jobber sync, and customer/owner SMS.",
      },
      {
        heading: "Retention",
        body: "We delete account data on request. Payment records may be retained as required by law.",
      },
      {
        heading: "SMS & TCPA",
        body: "Service-related texts include opt-out instructions (Reply STOP). Message and data rates may apply. We store consent timestamps when you sign up or when your customers opt in on intake forms. Transactional texts (booking updates, verification codes) require consent. Promotional texts (offers, maintenance reminders, review requests) require a separate optional opt-in.",
      },
      {
        heading: "Marketing communications",
        body: "You may optionally opt in to Effiroad product tips by email or text at signup. Customers may optionally opt in to promotional texts on link intake forms. You can opt out anytime via STOP (SMS) or by emailing support.",
      },
      {
        heading: "Cookies & essential storage",
        body: "We use essential cookies for login sessions, locale preference, and OAuth state (e.g. Jobber). We do not use advertising cookies. See your browser settings to clear cookies.",
      },
      {
        heading: "Your rights (US)",
        body: "California residents may request access or deletion of personal information by emailing support. We do not sell personal data.",
      },
      {
        heading: "Contact",
        body: `Privacy questions: ${SITE.supportEmail}`,
      },
    ],
  },
  terms: {
    title: "Terms of Service",
    updated: "July 2026",
    sections: [
      {
        heading: "Service",
        body: "Effiroad provides after-hours and overflow call intake, owner approval workflows, and crew notification tools for independent restoration and HVAC shops. CRM integration is optional. The service is a software tool — not an emergency services provider, contractor, insurer, or answering service that guarantees human pickup.",
      },
      {
        heading: "No guarantee (AS IS)",
        body: 'Effiroad is provided "AS IS" and "AS AVAILABLE." We do not guarantee that inbound calls will be answered, forwarded, recorded, transcribed, classified, or dispatched at any particular time, speed, or accuracy. Outages, carrier issues, misconfigured call forwarding, third-party API failures, and incorrect AI intake may occur. You must verify forwarding with a test call and monitor live traffic.',
      },
      {
        heading: "Your responsibility",
        body: "You remain solely responsible for all dispatch, scheduling, pricing, safety, licensing, and customer communication decisions. Effiroad captures intake and sends notifications — it does not replace your judgment. Fire, sewage, gas smell, and other high-risk situations may require your explicit approval before dispatch, per your settings.",
      },
      {
        heading: "Third-party services",
        body: "The service relies on third parties (phone carriers, Twilio, Retell, cloud hosting, SMS gateways). We are not liable for failures caused by those providers, your phone or forwarding settings, power or network outages, or configuration errors on your side.",
      },
      {
        heading: "Free pilots & evaluations",
        body: "Free trials and evaluation periods are best-effort only with no service-level agreement (SLA). Either party may stop at any time. Pilot access does not create a partnership, employment, or agency relationship.",
      },
      {
        heading: "Limitation of liability",
        body: "To the maximum extent permitted by law, Effiroad's total liability for any claim arising from the service is limited to the fees you paid us in the twelve (12) months before the claim (or USD $100 if you are on a free trial and paid nothing). We are not liable for lost profits, lost jobs, missed calls, business interruption, property damage, or any indirect, incidental, special, or consequential damages — even if we were advised such damages were possible.",
      },
      {
        heading: "Indemnification",
        body: "You agree to indemnify and hold Effiroad harmless from claims, damages, and expenses (including reasonable legal fees) arising from your use of the service, your dispatch or business decisions, your customers, or your violation of these terms or applicable law.",
      },
      {
        heading: "Billing",
        body: "Paid plans bill via Lemon Squeezy. Choose dispatch billing (Lite/Flex per approved emergency job; Pro/Scale with included caps) or Voice per-minute plans. Free estimate calls (press 2) are never billed. We SMS at 80% and 100% of included caps before overage.",
      },
      {
        heading: "SMS & messaging",
        body: "You are responsible for obtaining consent before texting your customers. Effiroad provides intake consent checkboxes and STOP handling. You must register your business for A2P/10DLC messaging with your carrier as required.",
      },
      {
        heading: "Contact",
        body: `Terms questions: ${SITE.supportEmail}`,
      },
    ],
  },
  refund: {
    title: "Refund Policy",
    updated: "July 2026",
    sections: [
      {
        heading: "30-day money-back guarantee",
        body: "Every Effiroad subscription includes a 30-day money-back guarantee. If you're not satisfied within the first 30 days of your first paid subscription, email us and we'll refund your most recent subscription payment in full.",
      },
      {
        heading: "How to request a refund",
        body: `Email ${SITE.supportEmail} from the address on your account with your business name. We process eligible refunds to your original payment method, typically within 5–10 business days via Lemon Squeezy, our payment provider and Merchant of Record.`,
      },
      {
        heading: "Cancellations",
        body: "You can cancel anytime — there are no contracts or cancellation fees. Cancelling stops future renewals; your service remains active until the end of the current billing period. Amounts already billed for the current period are non-refundable except under the 30-day guarantee above.",
      },
      {
        heading: "Flex plan (per-dispatch) charges",
        body: "On the Flex plan, per-approved-dispatch charges reflect service already delivered and are non-refundable, except where a charge was made in error — in which case we will correct it promptly.",
      },
      {
        heading: "Contact",
        body: `Refund or billing questions: ${SITE.supportEmail}`,
      },
    ],
  },
};

/** Full English dashboard UI — merges over Korean base for any missing keys. */
export function buildDashboardUiEn<T extends Record<string, unknown>>(ko: T): T {
  const bd = (ko.bookingDetail ?? {}) as Record<string, string | ((...args: never[]) => string)>;
  return {
    ...ko,
    hero: {
      ...(ko.hero as object),
      loading: "Loading…",
      ariaLabel: "Service requests this month",
      serviceRequestsThisMonth: "Service requests this month",
      sameAsLastMonth: "Same as last month",
      vsLastMonthUp: (n: number) => `+${n} vs last month`,
      vsLastMonthDown: (n: number) => `${n} vs last month`,
      updating: "Updating…",
      callsLine: (calls: number, conversion: number) =>
        calls > 0 ? `${calls} calls · ${conversion}% conversion` : `${calls} calls`,
      dailyRequests: "Daily requests",
      inboundCalls: "Inbound calls",
      conversion: "Conversion",
      emergenciesP1: "Emergency (P1)",
      emptyConnected:
        "No service requests this month yet. They appear here after AI intake.",
      emptyNotConnected:
        "No requests yet. Connect Jobber or enable call intake to start tracking.",
    },
    recentBookings: {
      ...(ko.recentBookings as object),
      liveFeed: "Live",
      title: "Recent bookings",
      subtitle: "Latest service requests — newest first",
      viewAll: "View all",
      couldntLoad: "Couldn't load bookings",
      emptyTitle: "No requests yet",
      emptyBody:
        "Inbound calls and Jobber requests appear here after AI intake. If you're not live yet, finish call forwarding in Settings.",
      emptyCta: "Start go-live in Settings",
    },
    smsFailureAlert: {
      title: "SMS delivery failed",
      fixSettings: "Twilio · contact settings",
      dismiss: "Dismiss",
    },
    notifications: {
      ...(ko.notifications as object),
      activity: "Activity",
      panelTitle: "Notifications",
      panelSubtitle: "Emergencies and new requests first",
      toReview: (n: number) => `${n} to review`,
      allBookingsLink: "All requests",
      bellAria: (unread: number) =>
        unread > 0 ? `Notifications, ${unread} unread` : "Notifications",
      upToDate: "Up to date",
      unreadCount: (n: number) => `${n}`,
      dropdownTitle: "Notifications",
      needAttention: (n: number) => `${n} need attention`,
      youreUpToDate: "You're all caught up",
      markAllRead: "Mark all read",
      markAllReadShort: "Mark all read",
      delete: "Delete",
      deleteAll: "Delete all",
      deleteSelected: "Delete selected",
      deleteSelectedConfirm: (n: number) => `Delete selected (${n})`,
      cancelSelect: "Cancel",
      confirmDeleteAll: "Delete all notifications?",
      eventCount: (n: number) => `${n}`,
      couldntLoad: "Couldn't load activity",
      allCaughtUp: "You're all caught up",
      emptyAll: "New requests, calls, and Jobber events show up here.",
      emptyFilter: "Nothing in this category right now.",
      unreadAria: "Unread",
      filters: {
        all: "All",
        bookings: "Requests",
        emergency: "Emergency",
        callbacks: "Callbacks",
        jobber: "Jobber",
        voicemail: "Voicemail",
      },
    },
    shopTools: {
      title: "Shop tools",
      subtitle: "Integrations, Job Card, call logs",
    },
    customerVerificationKpi: {
      label: "Customer verification rate",
      shortHint: "Customer Verification Rate",
      periodLabel: "Based on confirmation text replies",
    },
    kpiDrilldown: {
      ...(ko.kpiDrilldown as object),
      eyebrow: "Drill-down",
      waitingPeriod: "Awaiting review now",
      periodSum: (range: string) => `Selected period ${range}`,
      count: (n: number) => `${n}`,
      empty: "No items in this category.",
      close: "Close",
      viewAllBookings: "View all requests →",
      tapHint: "Click to view list",
    },
    bookingDetail: {
      ...bd,
      backToList: "← All requests",
      pendingReviewTitle: "Your review is needed",
      pendingReviewBody:
        "Not a confirmed visit yet. Approve or decline after reviewing. Approving may text the customer, offer the job to crew (if enabled), and sync Jobber when connected.",
      approvedBanner: "Approved",
      approvedBannerBody: "Status saved. You can update schedule or completion below.",
      rejectedBanner: "Declined",
      rejectedBannerBody: "Saved to your request history.",
      currentStatus: (label: string) => `Status: ${label}`,
      decisionTitle: "Your decision",
      decisionSubtitle: "Saved to your request history.",
      approve: "Approve",
      reject: "Decline",
      confirmApproveTitle: "Approve this request?",
      confirmApproveBody:
        "Customer may get a confirmation text. If crew dispatch is on, a tech offer SMS may go out. Jobber syncs when connected.",
      confirmRejectTitle: "Decline this request?",
      confirmRejectBody: "The customer may receive a decline notice.",
      confirm: "Confirm",
      cancel: "Cancel",
      saving: "Saving…",
      serviceRequest: "Service request",
      callCustomer: "Call customer",
      noPhone: "No phone on file",
      openJobber: "Open in Jobber",
      jobberUnavailable: "No Jobber link",
      markScheduled: "Mark scheduled",
      markCompleted: "Mark completed",
      customerInfo: "Customer",
      requestInfo: "Request details",
      name: "Name",
      phone: "Phone",
      address: "Address",
      cityState: "City / state",
      zip: "ZIP",
      issueType: "Issue",
      priority: "Priority",
      changePriority: "Change priority",
      requestDateTime: "Received",
      status: "Status",
      customerPreference: "Customer preference",
      priorityReasonTitle: "Priority reasons",
      priorityReasonAi: "AI classification from full call transcript",
      priorityReasonManual: "AI + manual override — change priority above",
      callSummaryTitle: "Call summary",
      callSummaryLinked: "AI intake — verified before request was created",
      callSummaryUnlinked: "AI intake — not a confirmed visit",
      transcriptTitle: "Transcript",
      transcriptSubtitle: "Full conversation",
      transcriptEmpty: "No transcript for this request.",
      recordingTitle: "Recording",
      recordingSubtitle: "Listen to original call",
      recordingEmpty: "No recording. Enable Twilio recording to save calls.",
      audioUnsupported: "Your browser cannot play this audio.",
      trustScore: "Trust score",
      trustScoreBenchmark: "80+ is sufficient",
      trustScoreSufficient:
        "80 or higher — core details look solid. Review and approve as usual.",
      trustScoreHigh: "Nearly everything verified. Safe to approve quickly.",
      trustScoreBelow:
        "Below 80 — double-check name, address, and phone before approving.",
      trustCriteriaMet: (n: number, total: number) =>
        `${n} of ${total} checks met (linked call)`,
      trustNoCall: "No linked call — limited verification data",
      trustNoCallGuide: "No call linked. Verify customer details manually.",
      customerVerificationTitle: "Customer verification",
      customerVerificationNone: "No confirmation text sent (link intake only).",
      verificationTitle: "Verification",
      verificationLinked: "Linked call — intake and trust signals",
      verificationUnlinked: "No linked call — no verification data",
      loadFailed: "Couldn't load request",
      notFoundTitle: "Request not found",
      notFoundBody: "It may have been removed or the link is invalid.",
      viewAll: "View all requests",
      statusUpdateFailed: "Couldn't save status.",
      statusNetworkError: "Network error while saving status.",
      priorityUpdateFailed: "Couldn't save priority.",
      priorityNetworkError: "Network error while saving priority.",
    },
    loadErrors: {
      ...(ko.loadErrors as object),
      bothFailed: "Couldn't load bookings. Check your connection and retry.",
      callsFailed: "Couldn't load call logs — showing saved requests only.",
      jobsFailed: "Couldn't load jobs — some requests may be missing.",
      network: "Network error while loading bookings.",
      statusKv: "Request status storage unavailable. Connect Vercel KV.",
      statusFailed: "Couldn't load request statuses.",
      jobberTimeout: "Jobber sync timed out — showing calls and saved jobs only.",
      jobberFailed: "Jobber sync failed — showing calls and saved jobs only.",
    },
    notificationEvents: {
      reviewRequest: "Service request to review",
      emergency: "Emergency call received",
      callback: "Callback requested",
      voicemail: "New voicemail",
      jobberFail: "Jobber sync failed",
      p1Emergency: "P1 emergency",
      followUp: "Follow-up requested",
      recordingReady: "Recording ready",
      messageCaptured: "Message captured",
      approved: "Request approved",
      rejected: "Request declined",
      scheduled: "Marked scheduled",
      completed: "Marked completed",
      requestReceived: "Service request received",
      intakeFailed: "Intake failed",
      smsFailed: "SMS delivery failed",
      caller: "Caller",
      inboundCall: "Inbound call",
    },
    missedCallsPrevented: {
      title: "Leads captured",
      today: "Today",
      last7: "Last 7 days",
      last30: "Last 30 days",
      allTime: "All time",
      helper:
        "Calls answered after hours or when your team was unavailable — leads you would have lost to voicemail.",
      viewAnalytics: "View analytics →",
    },
    missedCallsAnalytics: {
      eyebrow: "Value",
      title: "Leads captured",
      subtitle:
        "Customers captured by Effiroad during missed calls, after-hours, and unavailable periods.",
      backToDashboard: "← Back to dashboard",
      refresh: "Refresh",
      refreshing: "Loading…",
      periodSum: "Selected period total",
      periodPresets: [
        { id: "today" as const, label: "1d" },
        { id: "7d" as const, label: "7d" },
        { id: "30d" as const, label: "30d" },
        { id: "6m" as const, label: "6mo" },
        { id: "1y" as const, label: "1yr" },
      ],
      chartTitle: "Trends",
      chartSubtitle: "Same metrics as chart legend · from call and request logs",
      chartEmpty: "No captured calls in this period.",
      loadingChart: "Loading…",
      chartAria: "Daily leads captured trend",
      chartTooltip: (n: number) => `${n} captured`,
      withoutEffiroad: "Without Effiroad",
      estimatedMissed: "Estimated missed calls",
      estimatedMissedBody:
        "Calls Effiroad answered after hours or when you were unavailable — likely voicemail otherwise.",
      periodNote: (period: string) => `${period} · updates when new calls sync`,
      howCalculated: "Data scope & methodology",
      howCalculatedBody:
        "All metrics reflect calls handled directly by Effiroad AI within your configured answer windows. Calls that reach your shop line outside those windows are not routed through Effiroad and are therefore not included in these figures. Leads captured = inbound calls answered by AI. Bookings = service requests approved or scheduled during the selected period. Call recordings and customer details are encrypted at rest and accessible only from your dashboard.",
      pageBadge: "Analytics",
    },
    ops: {
      today: "Today",
      last7: "7d",
      last30: "30d",
      last90: "90d",
      last6m: "6mo",
      last1y: "1yr",
      customRange: "Custom",
      justNow: "Just now",
      totalBookings: "Total requests",
      emergencyCalls: "Emergency calls",
      conversionRate: "Conversion",
      afterHours: "After hours",
      bookingTrend: "Booking trend",
      trendSubtitleJobber: "Jobber requests + Effiroad bookings",
      trendSubtitle: "Confirmed requests in period",
      noBookingsInRange: "No requests in this period.",
      trendWeeklyHint: "Monday-based · weekly totals (bars)",
      trendMonthlyHint: "Monthly totals (bars)",
      trendTooltipBookings: (n: number) => `${n} requests`,
      trendTooltipCalls: (n: number) => `${n} calls`,
      hourly: "By hour",
      hourlySub: "Inbound calls (local time)",
      dayOfWeek: "By day of week",
      dayOfWeekSub: "Call volume by weekday",
      emergencyBreakdown: "Priority mix",
      emergencySub: "P1 / P2 / P3 from calls and Job Cards",
      zipAnalysis: "ZIP codes",
      zipSub: "Service area from call and job addresses",
      activityFeed: "Recent activity",
      activitySub: "Latest calls and requests",
      insights: "Operational insights",
      insightsSub: "Selected period vs previous period",
      noActivity: "No activity in this period.",
      operationalInsights: "Operational insights",
    },
    pendingReview: {
      title: "Pending approval",
      subtitle: "Text 1 REF to approve or 2 REF to decline. One pending? Just 1 or 2 works.",
      approve: "Approve",
      reject: "Decline",
      empty: "No requests waiting for review.",
      refLabel: "Ref",
      working: "Saving…",
    },
  } as T;
}
