import { SITE } from "./constants";
import { SETTINGS_PAGE_EN } from "./content-settings-en-backup";

export const settingsPageEn = {
  ...SETTINGS_PAGE_EN,
  bookingPolicyMode: "Customer slot pick",
  bookingPolicyDescription:
    "Customers pick a visit window on the call. Speed auto-confirms; Hybrid/Control may need your text approval before Jobber sync.",
  bookingModeSpeedDesc:
    "Customer picks a slot — booking confirms without owner approval. You get an FYI text; reply 9 to undo within the undo window.",
  bookingModeHybridDesc:
    "Check P1/P2/P3 to auto-confirm like Speed. Unchecked priorities need your 1/2 text approval. Selecting all three switches to Auto Book mode.",
  hybridAutoPrioritiesLabel: "Hybrid — auto-confirm these priorities",
  hybridAutoPrioritiesHint:
    "Checked priorities book instantly. Unchecked ones wait for manual approval. All three checked = Auto Book mode.",
  hybridAllSelectedNote:
    "P1, P2, and P3 all auto-confirm (Auto Book). Pick Hybrid to auto-book only some priorities.",
  bookingModeControlDesc:
    "Every picked slot waits for owner approval. You get a text — reply 1=approve, 2=reject.",
  slotOfferCountLabel: "Slots shown to customer",
  slotOfferCountHint: "How many visit windows to offer on calls and SMS links (1–5).",
  undoWindowLabel: "Undo window (minutes)",
  undoWindowHint: "After auto-book, reply 9 within this window to cancel and move back to review.",
  shadowModeLabel: "Practice mode (test calls remaining)",
  shadowModeIntro: "Test the call flow without writing to Jobber or sending customer texts.",
  shadowModeLive: "0 — Live: real calendar, SMS, and Jobber writes.",
  shadowModePractice:
    "1+ — Practice: full AI flow but no customer confirm SMS or calendar writes. Counts down per test call.",
  sectionSteps: {
    contact: "1",
    schedule: "2",
    phone: "3",
    jobber: "4",
  } as const,
};

export const vowDashboardEn = {
  nav: {
    dashboard: "Dashboard",
    briefing: "Daily Briefing",
    ai: "Vowpath AI",
    requests: "Requests",
    calendar: "Calendar",
    missedCalls: "Analytics",
    settings: "Integrations",
    shopTools: "Shop tools",
  },
  calendar: {
    title: "Schedule calendar",
    subtitle: "Tap a date for that day's visits, then tap a booking for details.",
    refresh: "Refresh",
    loading: "Loading…",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    today: "Today",
    noEventsDay: "No bookings",
    selectDay: "Select a date to see visits here.",
    dayEventsTitle: (count: number) => `${count} booking${count === 1 ? "" : "s"}`,
    noEventsOnDay: "No bookings on this day.",
    backToDayList: "← Back to list",
    eventCount: (count: number) => `${count}`,
    sourceVowpath: "Vowpath confirmed",
    sourceJobber: "Jobber",
    customer: "Customer",
    phone: "Phone",
    address: "Address",
    issue: "Issue",
    time: "Visit time",
    priority: "Priority",
    viewBooking: "View request",
    close: "Close",
    vowpathBookings: "Vowpath confirmed",
    jobberCalendar: "Jobber schedule",
    emptyNative: "No confirmed Vowpath visits yet.",
    emptyJobber: "No Jobber events or connection needed.",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] as const,
  },
  upgrade: {
    title: "Upgrade plan",
    body: "Unlimited after-hours AI answering and text approvals.",
    cta: "View plans",
  },
  header: {
    newRequest: "New request",
    dateRange: (start: string, end: string) => `${start} – ${end}`,
    dateQuick: "Quick range",
    dateCustom: "Custom",
    dateFrom: "From",
    dateTo: "To",
    dateApply: "Apply",
    dateInvalid: "Start date must be before end date.",
    subtitle: "Calls answered and jobs waiting on your reply.",
    simulateWorking: "AI processing… (10–20 sec)",
    simulateDone: "Test request created. Refreshing list.",
    simulateFail: "Could not create request. Check login and dev server.",
  },
  hero: {
    period: "This month",
    tagline: "Review and approve after-hours calls by text.",
    callsSaved: "Leads captured",
    aiAnswered: "AI answered calls",
    emergency: "Emergency requests",
    deltaFlat: "Same as prior month",
    delta: (pct: number) => `vs prior month ${pct > 0 ? "↑" : "↓"} ${Math.abs(pct)}%`,
  },
  secondary: {
    hint: "At a glance",
    body: "Numbers are from real call logs. New requests appear in the list below.",
  },
  kpi: {
    missedPrevented: "Leads captured",
    emergency: "Emergency",
    conversion: "Booking conversion",
    aiAnswered: "AI answered",
    vsPrior: (pct: number, period: string) =>
      pct === 0 ? `${period} · same as prior month` : `${period} · prior month ${pct > 0 ? "↑" : "↓"} ${Math.abs(pct)}%`,
  },
  compareLabel: "This month",
  trend: {
    title: "Trends",
    last30: "Last 30 days · daily",
    viewDetail: "View details",
  },
  insights: {
    title: "Call insights",
    thisMonth: "This month",
    delta: (pct: number) => (pct === 0 ? "—" : `${pct > 0 ? "↑" : "↓"} ${Math.abs(pct)}%`),
  },
  recentRequests: {
    title: "Recent requests",
    subtitle: "New customer inquiries — check first",
    viewAll: "View all",
    columns: {
      customer: "Customer",
      type: "Type",
      priority: "Priority",
      received: "Received",
      status: "Status",
    },
    empty: "No requests yet.",
  },
  upcoming: {
    title: "Upcoming · approved",
    empty: "No approved or scheduled visits yet.",
    confirmed: "Confirmed",
    pending: "In review",
  },
  tools: {
    title: "Tools",
    subtitle: "Job Card, call logs, integrations",
  },
};

export const dashboardPageEn = {
  title: "Dashboard",
  subtitle: "After-hours and overflow calls in one place. Emergencies surface by text first.",
  setupIncomplete: "Setup isn't finished. Complete integrations to start answering calls.",
  setupComplete: "Live — Vowpath answers on your schedule.",
  stats: {
    tonightCalls: "Tonight's calls",
    bookings: "Service requests",
    pendingApproval: "Pending approval",
  },
  scheduleTitle: "AI answer hours",
  scheduleEmpty: "No hours configured.",
  backOnboarding: "Finish setup",
};

export const authPagesEn = {
  form: {
    passwordConfirmLabel: "Confirm password",
    passwordMismatch: "Passwords don't match.",
    loading: "Working…",
    errorGeneric: "Request failed.",
    errorNetwork: "Network error. Try again.",
    backHome: "← Home",
  },
  login: {
    title: "Log in",
    subtitle: "Access your Vowpath dashboard.",
    methodLegend: "Sign in with",
    methodEmail: "Email",
    methodPhone: "Phone",
    emailLabel: "Email",
    phoneLabel: "Mobile number",
    phonePlaceholder: "(512) 555-0100",
    passwordLabel: "Password",
    submit: "Log in",
    noAccount: "No account?",
    signupLink: "Sign up",
    forgotLink: "Forgot password?",
    rememberMeLabel: "Keep me signed in on this device",
  },
  forgotPassword: {
    title: "Reset password",
    subtitleRequest: "We'll send a code to your email to set a new password.",
    subtitleRequestSms: "We'll text a code to your registered mobile number.",
    subtitleVerify: "Enter the 6-digit code from email or SMS.",
    subtitleReset: "Choose a new password.",
    subtitleDone: "Password updated.",
    emailLabel: "Email",
    phoneLabel: "Mobile number",
    phonePlaceholder: "(512) 555-0100",
    channelLabel: "Send code via",
    channelEmail: "Email",
    channelSms: "SMS",
    channelHint: "SMS goes only to your signup mobile number.",
    devEmailHint: "In local dev, check the terminal if email isn't configured.",
    sendCode: "Send code",
    codeLabel: "6-digit code",
    codeHint: "Enter within 10 minutes. Don't share this code.",
    verifyCode: "Verify",
    resendSms: "Resend SMS",
    resendSmsSuccess: "Code sent to your registered phone.",
    backToEmail: "← Re-enter email",
    newPasswordLabel: "New password",
    confirmPasswordLabel: "Confirm new password",
    resetPassword: "Update password",
    goLogin: "Log in",
    backLogin: "Back to login",
    sentMessage: "If an account exists, we sent a code.",
    doneMessage: "Password changed. Log in with your new password.",
    loading: "Working…",
    errorGeneric: "Request failed.",
    errorNetwork: "Network error. Try again.",
  },
  signup: {
    title: "Sign up",
    step1Label: "1. Your details",
    step2Label: "2. Verify",
    subtitle: "Enter your info, then tap Send code to verify.",
    subtitleVerify: "After verifying, tap Create account to finish.",
    shopLabel: "Shop name",
    shopPlaceholder: "e.g. Cool Air HVAC",
    emailLabel: "Email",
    passwordLabel: "Password",
    passwordHint: "8+ characters",
    phoneLabel: "Mobile number",
    phoneLabelRequired: "Mobile number (required)",
    phonePlaceholder: "(512) 555-0100",
    phoneHintRequired:
      "US mobile (+1) — used for new request texts and reply 1/2 approvals.",
    phoneHintSms: "We'll text your verification code here.",
    phoneRequired: "Enter your mobile number.",
    phoneRequiredSms: "Enter your mobile number for SMS verification.",
    verifyChannelLabel: "Send code via",
    verifyChannelEmail: "Email (recommended)",
    verifyChannelSms: "SMS",
    verifyChannelHint: "Code by email or SMS. Mobile is required above.",
    sendCode: "Send code",
    sendCodeNote: "Enter the 6-digit code, then tap Verify.",
    sendCodeCooldown: "Resend ({seconds}s)",
    sentCodeMessage: "Code sent. Check email or SMS.",
    codeLabel: "6-digit code",
    codeHint: "Enter within 10 minutes.",
    verifyCode: "Verify",
    verifiedMessage: "Verified. Tap Create account to finish.",
    completeSignup: "Create account",
    backToDetails: "← Edit details",
    hasAccount: "Already have an account?",
    loginLink: "Log in",
  },
};

export const legalPagesEn = {
  privacy: {
    title: "Privacy Policy",
    updated: "March 2026",
    sections: [
      {
        heading: "Information we collect",
        body: "Email, shop name, payment info (Stripe), Jobber metadata when connected, and call logs when intake is enabled.",
      },
      {
        heading: "How we use it",
        body: "To provide the service, billing, after-hours call handling, Jobber sync, and customer/owner SMS.",
      },
      {
        heading: "Retention",
        body: "We delete account data on request. Payment records may be retained as required by law.",
      },
      {
        heading: "SMS & TCPA",
        body: "Service-related texts include opt-out instructions (Reply STOP). Message and data rates may apply.",
      },
      {
        heading: "Contact",
        body: `Privacy questions: ${SITE.supportEmail}`,
      },
    ],
  },
  terms: {
    title: "Terms of Service",
    updated: "March 2026",
    sections: [
      {
        heading: "Service",
        body: "Vowpath provides after-hours call intake and owner approval workflows for HVAC shops. Jobber integration is optional.",
      },
      {
        heading: "Billing",
        body: "Paid plans bill via Stripe. Flex plan charges per approved booking as described at checkout.",
      },
      {
        heading: "Liability",
        body: "Emergency dispatch decisions remain with the shop owner. AI intake is a helper tool, not a guarantee of accuracy.",
      },
      {
        heading: "Contact",
        body: `Terms questions: ${SITE.supportEmail}`,
      },
    ],
  },
};

/** Full English dashboard UI — merges over Korean base for any missing keys. */
export function buildDashboardUiEn<T extends Record<string, unknown>>(ko: T): T {
  const bd = (ko.bookingDetail ?? {}) as Record<string, string | ((...args: never[]) => string)>;
  return {
    ...ko,
    hero: {
      ...(ko.hero as object),
      loading: "Loading…",
      ariaLabel: "Service requests this month",
      serviceRequestsThisMonth: "Service requests this month",
      sameAsLastMonth: "Same as last month",
      vsLastMonthUp: (n: number) => `+${n} vs prior month`,
      vsLastMonthDown: (n: number) => `${n} vs prior month`,
      updating: "Updating…",
      callsLine: (calls: number, conversion: number) =>
        calls > 0 ? `${calls} calls · ${conversion}% conversion` : `${calls} calls`,
      dailyRequests: "Daily requests",
      inboundCalls: "Inbound calls",
      conversion: "Conversion",
      emergenciesP1: "Emergency (P1)",
      emptyConnected:
        "No service requests this month yet. They appear here after AI intake.",
      emptyNotConnected:
        "No requests yet. Connect Jobber or enable call intake to start tracking.",
    },
    recentBookings: {
      ...(ko.recentBookings as object),
      liveFeed: "Live",
      title: "Recent bookings",
      subtitle: "Latest service requests — newest first",
      viewAll: "View all",
      couldntLoad: "Couldn't load bookings",
      emptyTitle: "No bookings yet",
      emptyBody: "Inbound calls and requests appear here after AI intake.",
    },
    smsFailureAlert: {
      title: "SMS delivery failed",
      fixSettings: "Twilio · contact settings",
      dismiss: "Dismiss",
    },
    notifications: {
      ...(ko.notifications as object),
      activity: "Activity",
      panelTitle: "Notifications",
      panelSubtitle: "Emergencies and new requests first",
      toReview: (n: number) => `${n} to review`,
      allBookingsLink: "All requests",
      bellAria: (unread: number) =>
        unread > 0 ? `Notifications, ${unread} unread` : "Notifications",
      upToDate: "Up to date",
      unreadCount: (n: number) => `${n}`,
      dropdownTitle: "Notifications",
      needAttention: (n: number) => `${n} need attention`,
      youreUpToDate: "You're all caught up",
      markAllRead: "Mark all read",
      markAllReadShort: "Mark all read",
      delete: "Delete",
      deleteAll: "Delete all",
      deleteSelected: "Delete selected",
      deleteSelectedConfirm: (n: number) => `Delete selected (${n})`,
      cancelSelect: "Cancel",
      confirmDeleteAll: "Delete all notifications?",
      eventCount: (n: number) => `${n}`,
      couldntLoad: "Couldn't load activity",
      allCaughtUp: "You're all caught up",
      emptyAll: "New requests, calls, and Jobber events show up here.",
      emptyFilter: "Nothing in this category right now.",
      unreadAria: "Unread",
      filters: {
        all: "All",
        bookings: "Requests",
        emergency: "Emergency",
        callbacks: "Callbacks",
        jobber: "Jobber",
        voicemail: "Voicemail",
      },
    },
    shopTools: {
      title: "Shop tools",
      subtitle: "Integrations, Job Card, call logs",
    },
    customerVerificationKpi: {
      label: "Customer verification rate",
      shortHint: "Customer Verification Rate",
      periodLabel: "Based on confirmation text replies",
    },
    kpiDrilldown: {
      ...(ko.kpiDrilldown as object),
      eyebrow: "Drill-down",
      waitingPeriod: "Awaiting review now",
      periodSum: (range: string) => `Selected period ${range}`,
      count: (n: number) => `${n}`,
      empty: "No items in this category.",
      close: "Close",
      viewAllBookings: "View all requests →",
      tapHint: "Click to view list",
    },
    bookingDetail: {
      ...bd,
      backToList: "← All requests",
      pendingReviewTitle: "Your review is needed",
      pendingReviewBody:
        "This is a service request, not a confirmed visit. Approve or decline after reviewing. Do not tell the customer a visit is scheduled until you approve.",
      approvedBanner: "Approved",
      approvedBannerBody: "Status saved. You can update schedule or completion below.",
      rejectedBanner: "Declined",
      rejectedBannerBody: "Saved to your request history.",
      currentStatus: (label: string) => `Status: ${label}`,
      decisionTitle: "Your decision",
      decisionSubtitle: "Saved to your request history.",
      approve: "Approve",
      reject: "Decline",
      confirmApproveTitle: "Approve this request?",
      confirmApproveBody: "The customer may receive a confirmation text.",
      confirmRejectTitle: "Decline this request?",
      confirmRejectBody: "The customer may receive a decline notice.",
      confirm: "Confirm",
      cancel: "Cancel",
      saving: "Saving…",
      serviceRequest: "Service request",
      callCustomer: "Call customer",
      noPhone: "No phone on file",
      openJobber: "Open in Jobber",
      jobberUnavailable: "No Jobber link",
      markScheduled: "Mark scheduled",
      markCompleted: "Mark completed",
      customerInfo: "Customer",
      requestInfo: "Request details",
      name: "Name",
      phone: "Phone",
      address: "Address",
      cityState: "City / state",
      zip: "ZIP",
      issueType: "Issue",
      priority: "Priority",
      changePriority: "Change priority",
      requestDateTime: "Received",
      status: "Status",
      customerPreference: "Customer preference",
      priorityReasonTitle: "Priority reasons",
      priorityReasonAi: "AI classification from full call transcript",
      priorityReasonManual: "AI + manual override — change priority above",
      callSummaryTitle: "Call summary",
      callSummaryLinked: "AI intake — verified before request was created",
      callSummaryUnlinked: "AI intake — not a confirmed visit",
      transcriptTitle: "Transcript",
      transcriptSubtitle: "Full conversation",
      transcriptEmpty: "No transcript for this request.",
      recordingTitle: "Recording",
      recordingSubtitle: "Listen to original call",
      recordingEmpty: "No recording. Enable Twilio recording to save calls.",
      audioUnsupported: "Your browser cannot play this audio.",
      trustScore: "Trust score",
      trustScoreBenchmark: "80+ is sufficient",
      trustScoreSufficient:
        "80 or higher — core details look solid. Review and approve as usual.",
      trustScoreHigh: "Nearly everything verified. Safe to approve quickly.",
      trustScoreBelow:
        "Below 80 — double-check name, address, and phone before approving.",
      trustCriteriaMet: (n: number, total: number) =>
        `${n} of ${total} checks met (linked call)`,
      trustNoCall: "No linked call — limited verification data",
      trustNoCallGuide: "No call linked. Verify customer details manually.",
      customerVerificationTitle: "Customer verification",
      customerVerificationNone: "No confirmation text sent (link intake only).",
      verificationTitle: "Verification",
      verificationLinked: "Linked call — intake and trust signals",
      verificationUnlinked: "No linked call — no verification data",
      loadFailed: "Couldn't load request",
      notFoundTitle: "Request not found",
      notFoundBody: "It may have been removed or the link is invalid.",
      viewAll: "View all requests",
      statusUpdateFailed: "Couldn't save status.",
      statusNetworkError: "Network error while saving status.",
      priorityUpdateFailed: "Couldn't save priority.",
      priorityNetworkError: "Network error while saving priority.",
    },
    loadErrors: {
      ...(ko.loadErrors as object),
      bothFailed: "Couldn't load bookings. Check your connection and retry.",
      callsFailed: "Couldn't load call logs — showing saved requests only.",
      jobsFailed: "Couldn't load jobs — some requests may be missing.",
      network: "Network error while loading bookings.",
      statusKv: "Request status storage unavailable. Connect Vercel KV.",
      statusFailed: "Couldn't load request statuses.",
      jobberTimeout: "Jobber sync timed out — showing calls and saved jobs only.",
      jobberFailed: "Jobber sync failed — showing calls and saved jobs only.",
    },
    notificationEvents: {
      reviewRequest: "Service request to review",
      emergency: "Emergency call received",
      callback: "Callback requested",
      voicemail: "New voicemail",
      jobberFail: "Jobber sync failed",
      p1Emergency: "P1 emergency",
      followUp: "Follow-up requested",
      recordingReady: "Recording ready",
      messageCaptured: "Message captured",
      approved: "Request approved",
      rejected: "Request declined",
      scheduled: "Marked scheduled",
      completed: "Marked completed",
      requestReceived: "Service request received",
      intakeFailed: "Intake failed",
      smsFailed: "SMS delivery failed",
      caller: "Caller",
      inboundCall: "Inbound call",
    },
    missedCallsPrevented: {
      title: "Leads captured",
      today: "Today",
      last7: "Last 7 days",
      last30: "Last 30 days",
      allTime: "All time",
      helper:
        "Calls answered after hours or when your team was unavailable — leads you would have lost to voicemail.",
      viewAnalytics: "View analytics →",
    },
    missedCallsAnalytics: {
      eyebrow: "Value",
      title: "Leads captured",
      subtitle:
        "Customers captured by Vowpath during missed calls, after-hours, and unavailable periods.",
      backToDashboard: "← Back to dashboard",
      refresh: "Refresh",
      refreshing: "Loading…",
      periodSum: "Selected period total",
      periodPresets: [
        { id: "today" as const, label: "1d" },
        { id: "7d" as const, label: "7d" },
        { id: "30d" as const, label: "30d" },
        { id: "6m" as const, label: "6mo" },
        { id: "1y" as const, label: "1yr" },
      ],
      chartTitle: "Trends",
      chartSubtitle: "Same metrics as chart legend · from call and request logs",
      chartEmpty: "No captured calls in this period.",
      loadingChart: "Loading…",
      chartAria: "Daily leads captured trend",
      chartTooltip: (n: number) => `${n} captured`,
      withoutVowpath: "Without Vowpath",
      estimatedMissed: "Estimated missed calls",
      estimatedMissedBody:
        "Calls Vowpath answered after hours or when you were unavailable — likely voicemail otherwise.",
      periodNote: (period: string) => `${period} · updates when new calls sync`,
      howCalculated: "How we count",
      howCalculatedBody:
        "From stored call and request logs only. Leads captured = inbound calls answered. Bookings = requests approved or scheduled in the period.",
      pageBadge: "Analytics",
    },
    ops: {
      today: "Today",
      last7: "7d",
      last30: "30d",
      last90: "90d",
      last6m: "6mo",
      last1y: "1yr",
      customRange: "Custom",
      justNow: "Just now",
      totalBookings: "Total requests",
      emergencyCalls: "Emergency calls",
      conversionRate: "Conversion",
      afterHours: "After hours",
      bookingTrend: "Booking trend",
      trendSubtitleJobber: "Jobber requests + Vowpath bookings",
      trendSubtitle: "Confirmed requests in period",
      noBookingsInRange: "No requests in this period.",
      trendWeeklyHint: "Monday-based · weekly totals (bars)",
      trendMonthlyHint: "Monthly totals (bars)",
      trendTooltipBookings: (n: number) => `${n} requests`,
      trendTooltipCalls: (n: number) => `${n} calls`,
      hourly: "By hour",
      hourlySub: "Inbound calls (local time)",
      dayOfWeek: "By day of week",
      dayOfWeekSub: "Call volume by weekday",
      emergencyBreakdown: "Priority mix",
      emergencySub: "P1 / P2 / P3 from calls and Job Cards",
      zipAnalysis: "ZIP codes",
      zipSub: "Service area from call and job addresses",
      activityFeed: "Recent activity",
      activitySub: "Latest calls and requests",
      insights: "Operational insights",
      insightsSub: "Selected period vs prior period",
      noActivity: "No activity in this period.",
      operationalInsights: "Operational insights",
    },
    pendingReview: {
      title: "Pending approval",
      subtitle: "Reply 1 or 2 by text, or approve here",
      approve: "Approve",
      reject: "Decline",
      empty: "No requests waiting for review.",
      refLabel: "Ref",
      working: "Saving…",
    },
  } as T;
}
