import type { ManoProvider, ManoReview, ManoServiceRequest } from "./types";

export const SEED_PROVIDERS: ManoProvider[] = [
  {
    id: "pro_seed_001",
    name: "Carlos Mendoza",
    phone: "+523312345678",
    whatsapp: "+523312345678",
    categories: ["plomeria", "manitas"],
    colonias: ["Chapalita", "Providencia", "Monraz"],
    bio: "Plomero certificado con 12 años en Guadalajara. Emergencias el mismo día.",
    yearsExperience: 12,
    rating: 4.9,
    reviewCount: 87,
    jobsCompleted: 214,
    verified: true,
    createdAt: "2025-06-01T10:00:00.000Z",
  },
  {
    id: "pro_seed_002",
    name: "Ana Ruiz Limpieza",
    phone: "+523339876543",
    whatsapp: "+523339876543",
    categories: ["limpieza"],
    colonias: ["Americana", "Lafayette", "Centro Histórico", "Santa Tere"],
    bio: "Equipo de limpieza profunda para casas y departamentos. Productos eco.",
    yearsExperience: 8,
    rating: 4.8,
    reviewCount: 142,
    jobsCompleted: 380,
    verified: true,
    createdAt: "2025-04-15T10:00:00.000Z",
  },
  {
    id: "pro_seed_003",
    name: "ElectroGDL — Miguel Torres",
    phone: "+523314567890",
    whatsapp: "+523314567890",
    categories: ["electricidad", "aire"],
    colonias: ["Zapopan Centro", "Colinas de San Javier", "Bugambilias"],
    bio: "Instalaciones eléctricas y minisplits. Presupuesto sin compromiso.",
    yearsExperience: 15,
    rating: 4.7,
    reviewCount: 56,
    jobsCompleted: 128,
    verified: true,
    createdAt: "2025-08-20T10:00:00.000Z",
  },
  {
    id: "pro_seed_004",
    name: "Jorge Manitas Express",
    phone: "+523318765432",
    categories: ["manitas", "pintura"],
    colonias: ["Tlaquepaque Centro", "Oblatos", "Miramar"],
    bio: "Reparaciones rápidas: muebles, puertas, muros y pintura.",
    yearsExperience: 6,
    rating: 4.6,
    reviewCount: 34,
    jobsCompleted: 95,
    verified: false,
    createdAt: "2025-11-01T10:00:00.000Z",
  },
  {
    id: "pro_seed_005",
    name: "Verde Jardines GDL",
    phone: "+523337654321",
    whatsapp: "+523337654321",
    categories: ["jardineria"],
    colonias: ["Country Club", "Ciudad del Sol", "La Calma"],
    bio: "Diseño, poda y mantenimiento de jardines residenciales.",
    yearsExperience: 10,
    rating: 4.9,
    reviewCount: 41,
    jobsCompleted: 112,
    verified: true,
    createdAt: "2025-07-10T10:00:00.000Z",
  },
];

export const SEED_REQUESTS: ManoServiceRequest[] = [
  {
    id: "req_seed_001",
    category: "plomeria",
    title: "Fuga bajo el fregadero",
    description: "Gotea constantemente desde ayer. Necesito revisión hoy si es posible.",
    colonia: "Chapalita",
    urgency: "hoy",
    customerName: "María G.",
    customerPhone: "+523331112233",
    status: "abierta",
    budgetMax: 800,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "req_seed_002",
    category: "limpieza",
    title: "Limpieza profunda departamento 80m²",
    description: "2 recámaras, sala, cocina. Mudanza reciente, hay polvo.",
    colonia: "Providencia",
    urgency: "esta_semana",
    customerName: "Roberto S.",
    customerPhone: "+523334445566",
    status: "con_ofertas",
    budgetMin: 600,
    budgetMax: 1200,
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
];

export const SEED_REVIEWS: ManoReview[] = [
  {
    id: "rev_001",
    requestId: "req_done_001",
    providerId: "pro_seed_001",
    rating: 5,
    comment: "Llegó en 40 minutos y arregló la fuga. Muy profesional.",
    customerName: "Laura P.",
    createdAt: "2026-02-10T18:00:00.000Z",
  },
  {
    id: "rev_002",
    requestId: "req_done_002",
    providerId: "pro_seed_002",
    rating: 5,
    comment: "Dejaron el depa impecable. Recomendados.",
    customerName: "Diego M.",
    createdAt: "2026-02-28T14:00:00.000Z",
  },
];
