export const MANO_STRINGS = {
  brand: "Mano",
  tagline: "Profesionales de confianza en Guadalajara",
  city: "Guadalajara, Jalisco",
  heroTitle: "Encuentra al profesional perfecto cerca de ti",
  heroSubtitle:
    "Plomería, limpieza, electricidad y más. Cotiza gratis, compara profesionales verificados y contrata con confianza.",
  ctaRequest: "Solicitar servicio gratis",
  ctaProvider: "Soy profesional",
  howItWorks: "¿Cómo funciona?",
  step1Title: "Describe tu necesidad",
  step1Desc: "Cuéntanos qué necesitas y en qué colonia. Toma menos de 2 minutos.",
  step2Title: "Recibe cotizaciones",
  step2Desc: "Profesionales verificados te envían precio y disponibilidad.",
  step3Title: "Contrata con confianza",
  step3Desc: "Elige la mejor opción. Pagas cuando el trabajo esté hecho.",
  trustTitle: "Por qué Guadalajara confía en Mano",
  trustVerified: "Profesionales verificados",
  trustVerifiedDesc: "Revisamos identidad y experiencia antes de activar perfiles.",
  trustLocal: "100% local",
  trustLocalDesc: "Solo profesionales que trabajan en tu zona.",
  trustNoFee: "Cotización gratis",
  trustNoFeeDesc: "Sin costo para solicitar. Pagas solo el servicio acordado.",
  categoriesTitle: "Servicios populares en GDL",
  statsProviders: "profesionales",
  statsJobs: "trabajos completados",
  statsRating: "calificación promedio",
  footer: "© Mano — Hecho para Guadalajara",
  navHome: "Inicio",
  navRequest: "Solicitar",
  navProviders: "Profesionales",
  navMyRequests: "Mis solicitudes",
  commissionNote: "Comisión del 15% solo cuando completas un trabajo.",
} as const;

export type ManoStrings = typeof MANO_STRINGS;
