/**
 * Source profile — the ONE place that knows what Toss Shopping's payload looks
 * like. Everything else in the collector is shape-agnostic, so a site change is
 * a JSON edit (regenerated by `npm run pricepulse:probe`), not a code change.
 */
import { createHash } from "node:crypto";

export type SearchMode = "json" | "html-embedded";

export type EndpointSpec = {
  method?: "GET" | "POST";
  /** May contain {{keyword}}, {{page}}, {{size}}, {{category}}. */
  url: string;
  query?: Record<string, string>;
  headers?: Record<string, string>;
  /** POST only. */
  body?: unknown;
};

export type SearchProfile = {
  mode: SearchMode;
  endpoint: EndpointSpec;
  /** Ordered candidates; first one resolving to a non-empty array wins. */
  itemsPath: string[];
  totalPath?: string[];
  pageSize: number;
  /** Canonical field → ordered candidate paths inside one item. */
  fields: Record<string, string[]>;
  /** Relative product URLs are resolved against this. */
  urlBase: string;
};

export type SourceProfile = {
  version: number;
  source: string;
  /** "unverified" until a real capture has been replayed through it. */
  status: "unverified" | "verified";
  verifiedAt?: string;
  notes?: string;
  search: SearchProfile;
  category?: Partial<SearchProfile>;
};

export const REQUIRED_FIELDS = ["externalId", "name", "price"] as const;

export function validateProfile(profile: SourceProfile): string[] {
  const errors: string[] = [];
  if (!profile?.search) return ["profile.search missing"];
  if (!profile.search.endpoint?.url) errors.push("profile.search.endpoint.url missing");
  if (!Array.isArray(profile.search.itemsPath) || profile.search.itemsPath.length === 0) {
    errors.push("profile.search.itemsPath must list at least one candidate path");
  }
  for (const field of REQUIRED_FIELDS) {
    const candidates = profile.search.fields?.[field];
    if (!Array.isArray(candidates) || candidates.length === 0) {
      errors.push(`profile.search.fields.${field} must list at least one candidate path`);
    }
  }
  if (!Number.isFinite(profile.search.pageSize) || profile.search.pageSize <= 0) {
    errors.push("profile.search.pageSize must be a positive number");
  }
  return errors;
}

/** "data.products[0].seller.name" → value, or undefined. */
export function getPath(root: unknown, path: string): unknown {
  if (!path) return root;
  let current: unknown = root;
  for (const rawSegment of path.split(".")) {
    if (current == null) return undefined;
    const match = /^([^[\]]*)((\[\d+\])*)$/.exec(rawSegment);
    if (!match) return undefined;
    const [, key, indexes] = match;
    if (key) {
      if (typeof current !== "object") return undefined;
      current = (current as Record<string, unknown>)[key];
    }
    if (indexes) {
      for (const idx of indexes.match(/\d+/g) ?? []) {
        if (!Array.isArray(current)) return undefined;
        current = current[Number(idx)];
      }
    }
  }
  return current;
}

/** First candidate path that yields a usable value. */
export function resolveField(
  item: unknown,
  candidates: string[],
  accept: (value: unknown) => boolean,
): { value: unknown; path: string | null } {
  for (const path of candidates) {
    const value = getPath(item, path);
    if (value !== undefined && value !== null && accept(value)) {
      return { value, path };
    }
  }
  return { value: undefined, path: null };
}

/** Every key path in an object, capped so a deep payload cannot blow up. */
export function keyPaths(value: unknown, prefix = "", depth = 0): string[] {
  if (depth > 4 || value == null || typeof value !== "object") return prefix ? [prefix] : [];
  if (Array.isArray(value)) {
    return value.length ? keyPaths(value[0], `${prefix}[]`, depth + 1) : [`${prefix}[]`];
  }
  const out: string[] = [];
  for (const key of Object.keys(value as Record<string, unknown>).sort()) {
    const child = (value as Record<string, unknown>)[key];
    const next = prefix ? `${prefix}.${key}` : key;
    if (child && typeof child === "object") out.push(...keyPaths(child, next, depth + 1));
    else out.push(next);
  }
  return out;
}

/**
 * Stable hash of an item's shape (keys only, never values). Stored per run;
 * when it changes, Toss changed the payload — alert before parsing silently
 * degrades.
 */
export function shapeFingerprint(item: unknown): string | null {
  if (item == null || typeof item !== "object") return null;
  const paths = keyPaths(item).sort();
  if (!paths.length) return null;
  return createHash("sha1").update(paths.join("|")).digest("hex").slice(0, 16);
}

export function renderTemplate(input: string, vars: Record<string, string | number>): string {
  return input.replace(/\{\{(\w+)\}\}/g, (whole, key: string) =>
    key in vars ? String(vars[key]) : whole,
  );
}
